name = "bug-reporter-api"
compatibility_date = "2023-09-01"
pages_build_output_dir = "dist"

[env.production]
name = "bug-reporter-api"

[[d1_databases]]
binding = "DB"
database_name = "bug-reporter-db"
database_id = "your-d1-database-id-here"

# R2 bucket for file uploads
[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "bug-reporter-uploads"

# Environment variables - DO NOT commit secrets!
# Use wrangler secret put to set these in production:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_EMAIL
# wrangler secret put CORS_ORIGINS

[vars]
# These will be overridden by secrets in production
ADMIN_EMAIL = "admin@example.com"
CORS_ORIGINS = "http://localhost:5173"
