repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.15
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--no-hashes", "--no-emit-project", "--all-extras", "--output-file=requirements-dev.txt"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-yaml
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: mixed-line-ending
        args:
          - --fix=lf

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^(docs)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: 
          - --fix
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.36.1
    hooks:
      - id: djlint
        args:
          - --reformat
          - --lint

  - repo: local
    hooks:
      - id: check-style-tags
        name: check for <style> tags in HTML
        entry: python
        args: [pre-commit-hooks/check_style_tags.py]
        language: python
        types: [html]
        pass_filenames: false  # <-- ADD THIS LINE
        verbose: true

  - repo: local
    hooks:
      - id: django-collectstatic
        name: Django Collect Static
        entry: bash -c 'if [ -z "$GITHUB_ACTIONS" ]; then uv run python manage.py collectstatic --noinput; fi'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        verbose: true
      - id: django-test
        name: Django Tests
        entry: bash -c 'if [ -z "$GITHUB_ACTIONS" ]; then uv run python manage.py test --failfast; fi'
        language: system
        types: [python]
        pass_filenames: false
        always_run: false  # Changed from true to false - only runs when explicitly called
        verbose: false
        stages: [manual]  # Only runs when explicitly requested


fail_fast: true
