# Generated by Django 1.9.2 on 2016-09-01 03:26


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0002_auto_20160828_0116"),
    ]

    operations = [
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="issue",
            name="screenshot",
            field=models.ImageField(blank=True, null=True, upload_to=b"screenshots"),
        ),
        migrations.AddField(
            model_name="points",
            name="issue",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.Issue"),
        ),
        migrations.AddField(
            model_name="points",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]

