# Generated by Django 1.9.2 on 2016-09-20 21:13


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_auto_20160909_1902"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.TextField()),
                ("url", models.URLField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to=b"logos")),
                ("clicks", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("twitter", models.CharField(max_length=30)),
                ("facebook", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="hunt",
            options={"ordering": ["-id"]},
        ),
    ]
