# Generated by Django 1.9.2 on 2016-09-20 21:15


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_auto_20160920_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="clicks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="twitter",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
