# Generated by Django 1.9.2 on 2016-09-20 21:18


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_auto_20160920_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.Domain",
            ),
        ),
    ]
