# Generated by Django 1.9.2 on 2016-09-30 07:17


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_issue_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="webshot",
            field=models.ImageField(blank=True, null=True, upload_to=b"webshots"),
        ),
        migrations.AddField(
            model_name="points",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.Domain",
            ),
        ),
        migrations.AlterField(
            model_name="points",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.Issue",
            ),
        ),
    ]

