# Generated by Django 1.9.2 on 2016-11-05 18:28


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_auto_20160930_0317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="screenshot",
            field=models.ImageField(default="", upload_to=b"screenshots"),
            preserve_default=False,
        ),
    ]
