# Generated by Django 1.9.2 on 2016-11-13 18:52


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_auto_20161105_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(default="domain", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
