# Generated by Django 1.9.2 on 2016-11-13 19:17


from django.db import migrations, models

import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_auto_20161113_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="screenshot",
            field=models.ImageField(upload_to=b"screenshots", validators=[website.models.validate_image]),
        ),
    ]

