# Generated by Django 1.9.2 on 2016-11-17 06:06


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_auto_20161113_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="github",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

