# Generated by Django 1.9.2 on 2017-06-06 20:49


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0025_auto_20170605_1909"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]

