# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-07 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0026_auto_20170606_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='first_duplicate_report_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_report_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='marked_duplicate_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='marked_duplicate_count',
            field=models.IntegerField(default=0),
        ),
    ]
