# Generated by Django 1.9.2 on 2017-07-06 06:31


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0028_auto_20170705_2359"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.IntegerField(
                choices=[
                    (0, b"Unrated"),
                    (1, b"Bronze"),
                    (2, b"Silver"),
                    (3, b"Gold"),
                    (4, b"Platinum"),
                ],
                default=0,
            ),
        ),
    ]
