# Generated by Django 1.11.3 on 2017-07-22 22:32


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0033_issue_github_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="github_url",
            field=models.URLField(blank=True, default=b"", null=True),
        ),
    ]

