# Generated by Django 1.11.1 on 2017-08-12 23:51


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0034_auto_20170722_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follows",
            field=models.ManyToManyField(related_name="follower", to="website.UserProfile"),
        ),
    ]

