# Generated by Django 1.11.1 on 2017-08-13 00:49


import annoying.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0035_userprofile_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

