# Generated by Django 1.11.1 on 2017-08-17 01:59


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0039_auto_20170817_0148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="upvoted_by",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upvoted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upvoted",
                to="website.Issue",
            ),
        ),
    ]

