# Generated by Django 1.11.1 on 2017-08-17 02:02


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0040_auto_20170817_0159"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="upvoted_by",
            new_name="issue_upvoted",
        ),
    ]
