# Generated by Django 1.11.1 on 2017-09-07 16:05


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0043_auto_20170903_0650"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="issue_upvoted",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="issue_upvoted",
            field=models.ManyToManyField(blank=True, null=True, related_name="upvoted", to="website.Issue"),
        ),
    ]
