# Generated by Django 1.11.10 on 2018-03-14 20:32


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0044_auto_20170907_1605"),
    ]

    operations = [
        migrations.CreateModel(
            name="IP",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("address", models.CharField(blank=True, max_length=25, null=True)),
                ("user", models.CharField(blank=True, max_length=25, null=True)),
                ("issuenumber", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="issue_upvoted",
            field=models.ManyToManyField(blank=True, related_name="upvoted", to="website.Issue"),
        ),
    ]
