# Generated by Django 3.0.7 on 2020-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0054_auto_20200621_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hunt",
            name="prize",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]

