# Generated by Django 3.0.7 on 2020-06-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0055_auto_20200621_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="description_html",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
