# Generated by Django 3.0.7 on 2020-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0056_hunt_description_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hunt",
            name="description_html",
        ),
        migrations.AlterField(
            model_name="companyadmin",
            name="role",
            field=models.IntegerField(choices=[(0, "Admin"), (1, "Moderator")], default=0),
        ),
    ]

