# Generated by Django 3.0.8 on 2020-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0057_auto_20200621_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]

