# Generated by Django 3.0.8 on 2020-08-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0063_auto_20200826_0351"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="hunt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.Hunt",
            ),
        ),
    ]
