# Generated by Django 3.0.8 on 2020-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0064_issue_hunt"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
