# Generated by Django 3.0.8 on 2020-08-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0067_auto_20200827_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="hunt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.Hunt",
            ),
        ),
    ]
