# Generated by Django 4.1 on 2022-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0068_winner_hunt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="issue_flaged",
            field=models.ManyToManyField(blank=True, related_name="flaged", to="website.issue"),
        ),
    ]

