# Generated by Django 4.1 on 2022-12-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0070_alter_issue_label_issuescreenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuescreenshot",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screenshots",
                to="website.issue",
            ),
        ),
    ]
