# Generated by Django 4.1 on 2023-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0072_issue_is_hidden_userprofile_issues_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuescreenshot",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
