# Generated by Django 4.1 on 2023-06-04 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_company_company_id_company_managers_domain_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='rewarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default=uuid.UUID('a4e8625e-49af-46af-b11d-ed1377f1a39a'), editable=False, max_length=255, unique=True),
        ),
    ]
