# Generated by Django 4.1 on 2023-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0074_organization_organization_id_organization_managers_domain_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="organization_logos"),
        ),
        migrations.AddField(
            model_name="issue",
            name="rewarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_id",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
