# Generated by Django 4.1 on 2023-08-23 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0078_alter_issue_team_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscribed_domains",
            field=models.ManyToManyField(
                related_name="user_subscribed_domains", to="website.domain"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscribed_users",
            field=models.ManyToManyField(
                related_name="user_subscribed_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
