# Generated by Django 4.1 on 2023-08-29 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0079_userprofile_crypto_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="team_members",
            field=models.ManyToManyField(blank=True, related_name="reportmembers", to=settings.AUTH_USER_MODEL),
        ),
    ]
