# Generated by Django 4.2.8 on 2024-02-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0081_userprofile_issue_downvoted"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="reporter_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]

