# Generated by Django 5.0.2 on 2024-02-22 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0082_issue_reporter_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitefriend",
            name="referral_code",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="invitefriend",
            name="signup_completed",
            field=models.BooleanField(default=False),
        ),
    ]
