# Generated by Django 5.0.2 on 2024-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0083_alter_invitefriend_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="cve_id",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]

