# Generated by Django 5.0.2 on 2024-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0083_alter_invitefriend_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="crypto_address",
            new_name="bch_address",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="btc_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="eth_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
