# Generated by Django 5.0.2 on 2024-03-07 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0084_contributorstats"),
        ("website", "0084_issue_cve_id"),
    ]

    operations = []
