# Generated by Django 5.0.2 on 2024-02-24 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0085_merge_20240218_1322"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RequestAccess",
            new_name="RequestIssueAccess",
        ),
    ]
