# Generated by Django 5.0.2 on 2024-03-08 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0085_merge_0084_contributorstats_0084_issue_cve_id"),
        ("website", "0085_merge_20240307_1217"),
    ]

    operations = []

