# Generated by Django 5.0.3 on 2024-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0086_merge_20240308_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="cve_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]

