# Generated by Django 5.0.3 on 2024-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0086_merge_20240308_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="cve_score",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
