# Generated by Django 5.0.2 on 2024-03-21 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0087_monitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitor",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]

