# Generated by Django 5.0.2 on 2024-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0085_merge_20240218_1322"),
        ("website", "0087_merge_20240226_2025"),
    ]

    operations = []
