# Generated by Django 5.0.2 on 2024-03-07 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0082_requestaccess"),
        ("website", "0084_contributorstats"),
        ("website", "0087_merge_20240226_2025"),
    ]

    operations = []
