# Generated by Django 5.0.2 on 2024-03-21 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0087_issue_cve_score"),
        ("website", "0088_monitor_created_monitor_modified"),
    ]

    operations = []
