# Generated by Django 5.0.2 on 2024-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0089_merge_20240321_2353"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("bid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
