# Generated by Django 5.0.2 on 2024-04-20 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0090_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="link",
            new_name="issue_url",
        ),
        migrations.AddField(
            model_name="bid",
            name="current_bid",
            field=models.CharField(default="No current bid", max_length=30),
        ),
        migrations.AddField(
            model_name="bid",
            name="time_left",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.IntegerField(),
        ),
    ]
