# Generated by Django 5.0.3 on 2024-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0090_alter_domain_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["id"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="closed_issues",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="company",
            name="open_issues",
            field=models.JSONField(default=list),
        ),
    ]
