# Generated by Django 5.0.3 on 2024-05-11 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0090_alter_domain_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
    ]
