# Generated by Django 5.0.2 on 2024-04-22 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0090_alter_domain_managers"),
        ("website", "0091_rename_link_bid_issue_url_bid_current_bid_and_more"),
    ]

    operations = []
