# Generated by Django 5.0.2 on 2024-05-11 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0091_bid"),
        ("website", "0091_remove_company_company_id"),
    ]

    operations = []
