# Generated by Django 5.0.2 on 2024-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0092_merge_20240422_2352"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.CharField(default=" ", max_length=30),
        ),
    ]
