# Generated by Django 5.0.2 on 2024-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0092_merge_0091_bid_0091_remove_company_company_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="user",
        ),
        migrations.AddField(
            model_name="bid",
            name="bch_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
