# Generated by Django 5.0.3 on 2024-05-08 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0092_alter_company_company_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("name", "url", "email")},
        ),
    ]
