# Generated by Django 5.0.6 on 2024-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0093_bid_bch_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="contact_info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="infringing_domain_name",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="infringing_domain_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="registration_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="serial_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
