# Generated by Django 5.0.3 on 2024-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0093_alter_company_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
