# Generated by Django 5.0.6 on 2024-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0094_chatbotlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
