# Generated by Django 5.0.2 on 2024-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0094_alter_bid_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.CharField(default="Add user", max_length=30),
        ),
    ]
