# Generated by Django 5.0.7 on 2024-07-14 17:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("website", "0096_suggestion"),
        ("website", "0097_rename_votes_suggestion_down_vote_suggestion_up_vote"),
    ]

    dependencies = [
        ("website", "0095_company_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("down_vote", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("up_vote", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
