# Generated by Django 5.0.6 on 2024-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0095_company_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("github_url", models.URLField()),
                ("wiki_url", models.URLField(blank=True, null=True)),
                ("homepage_url", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="project_logos"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

