# Generated by Django 5.0.7 on 2024-07-16 08:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0095_company_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                ("user", models.CharField(default="Add user", max_length=100)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("up_vote", models.IntegerField(blank=True, default=0, null=True)),
                ("down_vote", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuggestionLikes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="Add user", max_length=100)),
                ("up_vote", models.BooleanField(default=False)),
                ("down_vote", models.BooleanField(default=False)),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.suggestion",
                    ),
                ),
            ],
        ),
    ]
