# Generated by Django 5.0.7 on 2024-07-16 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0096_suggestion_suggestionlikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestion",
            name="name",
        ),
    ]
