# Generated by Django 5.0.7 on 2024-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0096_suggestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestion",
            old_name="votes",
            new_name="down_vote",
        ),
        migrations.AddField(
            model_name="suggestion",
            name="up_vote",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
