# Generated by Django 5.0.7 on 2024-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0096_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("github_id", models.IntegerField(unique=True)),
                ("github_url", models.URLField()),
                ("avatar_url", models.URLField()),
                ("contributor_type", models.CharField(max_length=255)),
                ("contributions", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(blank=True, null=True, related_name="projects", to="website.contributor"),
        ),
    ]

