# Generated by Django 5.0.2 on 2024-04-28 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0096_alter_bid_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bidsubmitter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(blank=True, default="Add user", max_length=30, null=True),
                ),
                (
                    "current_bid",
                    models.CharField(default="No current bid", max_length=30),
                ),
                ("time_left", models.DateTimeField(default=django.utils.timezone.now)),
                ("pr_link", models.URLField()),
            ],
        ),
    ]
