# Generated by Django 5.0.7 on 2024-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0096_moniterip_squashed_0097_rename_moniterip_monitorip"),
        ("website", "0097_contributor_project_contributors"),
    ]

    operations = []
