# Generated by Django 5.0.7 on 2024-07-25 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0097_contributor_project_contributors"),
        ("website", "0097_suggestion_suggestionvotes"),
    ]

    operations = []

