# Generated by Django 5.0.2 on 2024-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0097_bidsubmitter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidsubmitter",
            name="current_bid",
        ),
        migrations.RemoveField(
            model_name="bidsubmitter",
            name="time_left",
        ),
        migrations.AddField(
            model_name="bidsubmitter",
            name="bid_amount",
            field=models.IntegerField(default="0"),
        ),
    ]
