# Generated by Django 5.0.6 on 2024-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0098_alter_contributor_github_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="github_id",
            field=models.IntegerField(),
        ),
    ]
