# Generated by Django 5.0.2 on 2024-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0098_remove_bidsubmitter_current_bid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(default="Open", max_length=10),
        ),
    ]
