# Generated by Django 5.0.7 on 2024-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("website", "0099_blockedip_delete_monitorip"),
        ("website", "0100_ip_status"),
        ("website", "0101_ip_count_ip_user_agent_string"),
        ("website", "0102_alter_ip_status"),
        ("website", "0103_ip_ip_range"),
        ("website", "0104_rename_ip_blockedip_address_and_more"),
    ]

    dependencies = [
        ("website", "0098_merge_20240723_2307"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField(blank=True, null=True)),
                ("address_range", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent_string",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("count", models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name="MonitorIP",
        ),
        migrations.AddField(
            model_name="ip",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ip",
            name="user_agent_string",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ip",
            name="status",
            field=models.CharField(default="active", max_length=25),
        ),
        migrations.AddField(
            model_name="ip",
            name="address_range",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
