# Generated by Django 5.0.6 on 2024-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0100_alter_contributor_github_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="avatar",
            new_name="avatar_url",
        ),
        migrations.AlterField(
            model_name="contributor",
            name="contributions",
            field=models.PositiveIntegerField(),
        ),
    ]
