# Generated by Django 5.0.7 on 2024-07-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0099_blockedip_delete_monitorip_squashed_0104_rename_ip_blockedip_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ip",
            name="status",
        ),
    ]
