# Generated by Django 5.0.7 on 2024-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("website", "0106_remove_blockedip_address_range_and_more"),
        ("website", "0107_blockedip_reason_for_block"),
    ]

    dependencies = [
        ("website", "0105_remove_ip_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockedip",
            name="address_range",
        ),
        migrations.AddField(
            model_name="blockedip",
            name="address_range_end",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="address_range_start",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="reason_for_block",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
