# Generated by Django 5.0.7 on 2024-08-04 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0111_companyadmin_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AddField(
            model_name="contributorstats",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]

