# Generated by Django 5.0.7 on 2024-08-04 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0116_contributor_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bacontoken",
            old_name="date_awarded",
            new_name="created",
        ),
    ]
