# Generated by Django 5.0.7 on 2024-08-04 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0117_rename_date_awarded_bacontoken_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contribution",
            old_name="date_created",
            new_name="created",
        ),
    ]
