# Generated by Django 5.0.7 on 2024-08-05 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0121_ip_count_ip_method_ip_path_ip_referer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ip",
            old_name="user_agent_string",
            new_name="agent",
        ),
    ]
