# Generated by Django 5.0.7 on 2024-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0122_rename_user_agent_string_ip_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tags", to="website.tag"),
        ),
    ]

