# Generated by Django 5.0.8 on 2024-08-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0122_rename_user_agent_string_ip_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trademark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.domain",
                    ),
                ),
            ],
        ),
    ]
