# Generated by Django 5.0.8 on 2024-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0123_trademark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trademark",
            name="name",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
