# Generated by Django 5.1 on 2024-08-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0106_remove_blockedip_address_range_and_more_squashed_0107_blockedip_reason_for_block",
        ),
        ("website", "0124_company_tags_domain_tags_project_tags_and_more"),
    ]

    operations = []
