# Generated by Django 5.1 on 2024-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0124_company_tags_domain_tags_project_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "reason_for_block",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_range_start",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "address_range_end",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "user_agent_string",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("count", models.IntegerField(default=1)),
            ],
        ),
    ]
