# Generated by Django 5.0.7 on 2024-08-09 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0125_sizzle_issue_sizzle_activitylog_sizzle_screenshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sizzle_issue",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sizzle_screenshot",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="sizzle_timelog",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="sizzle_screenshot",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sizzle_timelog",
            name="user",
        ),
        migrations.AddField(
            model_name="issuescreenshot",
            name="is_activity_screenshot",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_title", models.CharField(max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="website.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelogs",
                        to="website.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Sizzle_ActivityLog",
        ),
        migrations.DeleteModel(
            name="Sizzle_Issue",
        ),
        migrations.DeleteModel(
            name="Sizzle_Screenshot",
        ),
        migrations.DeleteModel(
            name="Sizzle_TimeLog",
        ),
    ]
