# Generated by Django 5.1 on 2024-08-09 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0125_activitylog_timelog"),
        ("website", "0125_blockedip"),
    ]

    operations = []
