# Generated by Django 5.0.7 on 2024-08-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0127_tag_created_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="discounted_hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="x_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
