# Generated by Django 5.0.8 on 2024-08-12 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0124_alter_trademark_name"),
        ("website", "0128_userprofile_discounted_hourly_rate_and_more"),
    ]

    operations = []
