# Generated by Django 5.1 on 2024-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0128_userprofile_discounted_hourly_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blocked",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "reason_for_block",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("ip_network", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent_string",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("count", models.IntegerField(default=1)),
                ("created", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
