# Generated by Django 5.0.8 on 2024-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0128_userprofile_discounted_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
