# Generated by Django 5.0.8 on 2024-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0128_userprofile_discounted_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="contact_information",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="infringing_domain_name",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="issue",
            name="infringing_domain_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="registration_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="serial_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
