# Generated by Django 5.1 on 2024-08-12 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0127_blocked_delete_blockedip"),
        ("website", "0128_userprofile_discounted_hourly_rate_and_more"),
    ]

    operations = []
