# Generated by Django 5.0.8 on 2024-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0129_issue_contact_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="infringing_domain_name",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
