# Generated by Django 5.0.8 on 2024-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0130_alter_issue_infringing_domain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="infringing_domain_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="label",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "General"),
                    (1, "Number Error"),
                    (2, "Functional"),
                    (3, "Performance"),
                    (4, "Security"),
                    (5, "Typo"),
                    (6, "Design"),
                    (7, "Server Down"),
                    (8, "Trademark Squatting"),
                ],
                default=0,
            ),
        ),
    ]
