# Generated by Django 5.0.7 on 2024-08-13 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0132_alter_ip_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocked",
            name="created",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]

