# Generated by Django 5.0.8 on 2024-08-21 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0129_merge_20240812_1547"),
        ("website", "0134_blocked_modified"),
    ]

    operations = []
