# Generated by Django 5.0.8 on 2024-08-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0135_merge_0129_merge_20240812_1547_0134_blocked_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademark",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.company",
            ),
        ),
    ]
