# Generated by Django 5.0.8 on 2024-10-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0136_remove_companyadmin_company_remove_domain_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributor_count",
            field=models.IntegerField(default=0),
        ),
    ]
