# Generated by Django 5.0.8 on 2024-08-17 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0135_recommendation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recommendations",
            field=models.ManyToManyField(
                blank=True, related_name="recommended_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
