# Generated by Django 5.0.8 on 2024-08-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0136_userprofile_recommendations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="recommendations",
        ),
    ]
