# Generated by Django 5.0.8 on 2024-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0136_project_contributor_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="release_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="release_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

