# Generated by Django 5.0.8 on 2024-08-18 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0137_remove_userprofile_recommendations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("recommender", "recommended_user"), name="unique_recommendation"
            ),
        ),
    ]
