# Generated by Django 5.0.8 on 2024-10-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0137_project_release_datetime_project_release_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

