# Generated by Django 5.0.8 on 2024-10-12 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0138_project_last_updated"),
        ("website", "0138_project_total_issues"),
    ]

    operations = []
