# Generated by Django 5.1.2 on 2024-10-28 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0094_notification"),
        ("website", "0139_merge_20241012_2351"),
    ]

    operations = []
