# Generated by Django 5.0.8 on 2024-10-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0140_dailystatusreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_visit_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="repo_visit_count",
            field=models.IntegerField(default=0),
        ),
    ]

