# Generated by Django 5.1.2 on 2024-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0136_trademark_company"),
        ("website", "0141_project_project_visit_count_project_repo_visit_count"),
    ]

    operations = []
