# Generated by Django 5.1.1 on 2024-11-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0141_project_project_visit_count_project_repo_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="spam",
            field=models.BooleanField(default=False),
        ),
    ]
