# Generated by Django 5.1.1 on 2024-11-03 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0131_alter_issue_infringing_domain_name_alter_issue_label"),
        ("website", "0141_project_project_visit_count_project_repo_visit_count"),
    ]

    operations = []
