# Generated by Django 5.1.2 on 2024-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0141_project_project_visit_count_project_repo_visit_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="IpReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("malicious_activity_title", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "ip_type",
                    models.CharField(
                        choices=[("ipv4", "IPv4"), ("ipv6", "IPv6")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
