# Generated by Django 4.1 on 2024-10-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0141_project_project_visit_count_project_repo_visit_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="label",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "General"),
                    (1, "Number Error"),
                    (2, "Functional"),
                    (3, "Performance"),
                    (4, "Security"),
                    (5, "Typo"),
                    (6, "Design"),
                    (7, "Server Down"),
                    (8, "Trademark Squatting"),
                ],
                default=0,
            ),
        ),
    ]
