# Generated by Django 5.1.3 on 2024-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0141_project_project_visit_count_project_repo_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="views",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
