# Generated by Django 5.1.2 on 2024-11-05 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0142_ipreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipreport",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
