# Generated by Django 5.1.1 on 2024-11-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0142_remove_contributorstats_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorstats",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contributorstats",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
