# Generated by Django 5.1.3 on 2024-11-10 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0143_contributorstats_last_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IpReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_title", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("malicious", "Malicious"), ("friendly", "Friendly")],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "ip_type",
                    models.CharField(choices=[("ipv4", "IPv4"), ("ipv6", "IPv6")], max_length=10),
                ),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "reporter_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
