# Generated by Django 5.1.2 on 2024-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0143_ipreport_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipreport",
            name="reporter_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
