# Generated by Django 5.1.3 on 2024-11-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0142_ipreport"),
        ("website", "0143_contributorstats_last_updated_and_more"),
    ]

    operations = []
