# Generated by Django 5.1.1 on 2024-11-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0146_remove_contribution_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="github_username",
            field=models.CharField(default="", max_length=255),
        ),
    ]
