# Generated by Django 5.1.1 on 2024-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0147_contribution_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_commit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="license",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="open_pull_requests",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="primary_language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="watchers",
            field=models.IntegerField(default=0),
        ),
    ]

