# Generated by Django 5.1.3 on 2024-11-10 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0144_ipreport"),
        ("website", "0149_project_closed_issues_project_created_at_and_more"),
    ]

    operations = []

