# Generated by Django 5.1.1 on 2024-11-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0149_project_closed_issues_project_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="commit_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="latest_release",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

