# Generated by Django 5.1.3 on 2024-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0150_merge_20241110_0720"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributorStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("commits", models.IntegerField(default=0)),
                ("issues_opened", models.IntegerField(default=0)),
                ("issues_closed", models.IntegerField(default=0)),
                ("prs", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("assigned_issues", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
