# Generated by Django 5.1.3 on 2024-11-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0142_userprofile_views"),
        ("website", "0151_remove_project_latest_release"),
    ]

    operations = []
