# Generated by Django 5.1.3 on 2024-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0152_merge_20241112_1843"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="views",
        ),
        migrations.AddField(
            model_name="project",
            name="documentation_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="issue_tracker_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="recent_commit_messages",
            field=models.TextField(blank=True, null=True),
        ),
    ]
