# Generated by Django 5.1.3 on 2024-11-11 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0152_merge_20241111_0616"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContributorStats",
        ),
    ]

