# Generated by Django 5.1.3 on 2024-11-23 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0153_delete_contributorstats",
        ),  # Update with the correct last migration in your app
    ]

