# Generated by Django 5.1.3 on 2024-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0153_delete_contributorstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
