# Generated by Django 5.1.3 on 2024-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0154_project_ai_labels_project_ai_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="ai_labels",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
