# Generated by Django 5.1.3 on 2024-11-24 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0154_activity"),
        ("website", "0154_contributors_to_users_20241123_1836"),
    ]

    operations = []
