# Generated by Django 5.1.3 on 2024-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0154_recommendation_recommendation_unique_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recommendation_blurb",
            field=models.TextField(blank=True, null=True),
        ),
    ]
