# Generated by Django 5.1.3 on 2024-11-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0155_merge_20241124_0242"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="documentation_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="recent_commit_messages",
            field=models.TextField(blank=True, null=True),
        ),
    ]
