# Generated by Django 5.1.3 on 2024-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0155_userprofile_recommendation_blurb"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recommended_by",
            field=models.ManyToManyField(
                blank=True, related_name="has_recommended", to="website.userprofile"
            ),
        ),
    ]
