# Generated by Django 5.1.3 on 2024-11-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0155_merge_20241124_0242"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]

