# Generated by Django 5.1.3 on 2024-12-05 12:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0156_merge_20241205_1211"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.ImageField(blank=True, null=True, upload_to="badges/")),
                (
                    "type",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=10,
                    ),
                ),
                ("criteria", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_posted_to_bluesky",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_activities", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="recent_commit_messages",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timelog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="website.company",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("signup", "Signed Up"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        choices=[("slack", "SLACK")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_integrations",
                        to="website.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="integrations",
            field=models.ManyToManyField(related_name="companies", to="website.integration"),
        ),
        migrations.CreateModel(
            name="SlackIntegration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_access_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "workspace_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_channel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_channel_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("daily_updates", models.BooleanField(default=False)),
                (
                    "daily_update_time",
                    models.IntegerField(
                        blank=True,
                        help_text="The hour of the day (0-23) to send daily updates",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_integration",
                        to="website.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
