# Generated by Django 5.1.3 on 2024-11-25 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0156_alter_activity_action_type"),
        ("website", "0156_merge_20241124_0722"),
    ]

    operations = []
