# Generated by Django 5.1.4 on 2024-12-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0156_userprofile_recommended_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="recommendation_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
