# Generated by Django 5.1.3 on 2024-11-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0156_merge_20241124_0722"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="modified",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_suggestion_badge",
            field=models.BooleanField(default=False),
        ),
    ]
