# Generated by Django 5.1.3 on 2024-12-01 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0156_userprofile_visit_count"),
        ("website", "0158_badge_project_ai_summary_project_readme_content_and_more"),
    ]

    operations = []
