# Generated by Django 5.1.3 on 2024-11-28 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0157_merge_20241125_1005"),
        ("website", "0158_create_badges_1937"),
    ]

    operations = []

