# Generated by Django 5.1.3 on 2024-11-29 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0157_timelog_organization_alter_company_url"),
        ("website", "0159_merge_20241128_0439"),
    ]

    operations = []

