# Generated by Django 5.1.3 on 2024-12-01 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0156_userprofile_visit_count"),
        ("website", "0160_merge_20241129_0712"),
    ]

    operations = []

