# Generated by Django 5.1.3 on 2024-11-30 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0160_activity_dislike_count_activity_dislikes_and_more"),
        ("website", "0160_merge_20241129_0712"),
    ]

    operations = []
