# Generated by Django 5.1.3 on 2024-11-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0160_merge_20241129_0712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="badges/"),
        ),
    ]

