# Generated by Django 5.1.3 on 2024-12-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0160_merge_20241129_0712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="badges/"),
        ),
        migrations.AlterField(
            model_name="ip",
            name="agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
