# Generated by Django 5.1.3 on 2024-12-01 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0161_merge_20241130_0224"),
        ("website", "0162_add_new_badges"),
    ]

    operations = []

