# Generated by Django 5.1.3 on 2024-12-03 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0164_integration_company_integrations_slackintegration"),
        ("website", "0164_merge_20241201_1725"),
    ]

    operations = []

