# Generated by Django 5.1.3 on 2024-12-03 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0161_alter_badge_icon_alter_ip_agent"),
        ("website", "0164_integration_company_integrations_slackintegration"),
    ]

    operations = []
