# Generated by Django 5.1.3 on 2024-12-05 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0165_add_badge_icons"),
        ("website", "0165_merge_20241203_0320"),
    ]

    operations = []
