# Generated by Django 5.1.3 on 2024-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0166_merge_0165_add_badge_icons_0165_merge_20241203_0320"),
    ]

    operations = [
        migrations.AddField(
            model_name="points",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_check_in",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
    ]

