# Generated by Django 5.1.3 on 2024-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0166_merge_0165_add_badge_icons_0165_merge_20241203_0320"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="trademark",
            field=models.IntegerField(default=0),
        ),
    ]
