# Generated by Django 5.1.3 on 2024-12-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0169_dailystatusreport_current_mood_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.company",
            ),
        ),
    ]
