# Generated by Django 5.1.3 on 2024-12-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0167_team_userprofile_team"),
        ("website", "0169_dailystatusreport_current_mood_and_more"),
    ]

    operations = []
