# Generated by Django 5.1.3 on 2024-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0169_dailystatusreport_current_mood_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="recent_commit_messages",
            field=models.TextField(blank=True, null=True),
        ),
    ]
