# Generated by Django 5.1.3 on 2024-12-15 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0167_company_trademark"),
        ("website", "0169_dailystatusreport_current_mood_and_more"),
    ]

    operations = []
