# Generated by Django 5.1.3 on 2024-12-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0170_company_fresh_points_company_type_userprofile_team_and_more"),
        ("website", "0170_company_trademark_check_date_company_trademark_count"),
    ]

    operations = []
