# Generated by Django 5.1.3 on 2024-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0170_merge_20241215_1601"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="trademark",
            new_name="trademark_count",
        ),
        migrations.AddField(
            model_name="company",
            name="trademark_check_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
