# Generated by Django 5.1.3 on 2024-12-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0170_merge_20241216_0449"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
