# Generated by Django 5.1.3 on 2024-12-15 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0170_project_activity_status_project_is_github_repo_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdditionalRepo",
            new_name="Repo",
        ),
    ]
