# Generated by Django 5.1.3 on 2024-12-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0171_rename_additionalrepo_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="repos", to="website.contributor"
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repos",
                to="website.project",
            ),
        ),
    ]
