# Generated by Django 5.1.3 on 2024-12-18 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0171_company_team_points_company_type_userprofile_team_and_more"),
        ("website", "0171_post"),
    ]

    operations = []
