# Generated by Django 5.1.3 on 2024-12-19 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0170_project_ai_summary_project_readme_content_and_more"),
        ("website", "0172_merge_20241218_0505"),
    ]

    operations = []
