# Generated by Django 5.1.3 on 2024-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0172_merge_20241218_0505"),
    ]

    operations = [
        migrations.CreateModel(
            name="PRAnalysisReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_link", models.URLField()),
                ("issue_link", models.URLField()),
                ("priority_alignment_score", models.IntegerField()),
                ("revision_score", models.IntegerField()),
                ("recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

