# Generated by Django 5.1.3 on 2024-12-22 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0170_suggestion_company"),
        ("website", "0173_pranalysisreport"),
        ("website", "0173_remove_company_admin_remove_company_integrations_and_more"),
    ]

    operations = []
