# Generated by Django 5.1.3 on 2024-12-19 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0174_merge_20241219_1305"),
        ("website", "0174_merge_20241219_1316"),
    ]

    operations = []
