# Generated by Django 5.1.3 on 2024-12-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0174_merge_20241219_1305"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="closed_issues",
        ),
        migrations.RemoveField(
            model_name="project",
            name="commit_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contributor_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contributors",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="external_links",
        ),
        migrations.RemoveField(
            model_name="project",
            name="forks",
        ),
        migrations.RemoveField(
            model_name="project",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="homepage_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="last_commit_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="project",
            name="license",
        ),
        migrations.RemoveField(
            model_name="project",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="network_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="open_issues",
        ),
        migrations.RemoveField(
            model_name="project",
            name="open_pull_requests",
        ),
        migrations.RemoveField(
            model_name="project",
            name="primary_language",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_visit_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="release_datetime",
        ),
        migrations.RemoveField(
            model_name="project",
            name="release_name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="repo_visit_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="size",
        ),
        migrations.RemoveField(
            model_name="project",
            name="stars",
        ),
        migrations.RemoveField(
            model_name="project",
            name="subscribers_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="project",
            name="total_issues",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="watchers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="wiki_url",
        ),
        migrations.AddField(
            model_name="project",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="project_logos"),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="website.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="twitter",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("repo_url", models.URLField(unique=True)),
                ("homepage_url", models.URLField(blank=True, null=True)),
                ("is_main", models.BooleanField(default=False)),
                ("is_wiki", models.BooleanField(default=False)),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("open_issues", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("total_issues", models.IntegerField(default=0)),
                ("project_visit_count", models.IntegerField(default=0)),
                ("watchers", models.IntegerField(default=0)),
                ("open_pull_requests", models.IntegerField(default=0)),
                (
                    "primary_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("license", models.CharField(blank=True, max_length=100, null=True)),
                ("last_commit_date", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("network_count", models.IntegerField(default=0)),
                ("subscribers_count", models.IntegerField(default=0)),
                ("closed_issues", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("commit_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repos",
                        to="website.project",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="website.tag")),
            ],
        ),
    ]
