# Generated by Django 5.1.3 on 2024-12-22 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0170_suggestion_company"),
        ("website", "0174_merge_20241219_1305"),
    ]

    operations = []
