# Generated by Django 5.1.3 on 2024-12-19 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0173_remove_company_admin_remove_company_integrations_and_more"),
        ("website", "0175_add_team_challenges"),
    ]

    operations = []

