# Generated by Django 5.1.4 on 2025-01-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0177_kudos"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_visit_count",
            field=models.IntegerField(default=0),
        ),
    ]
