# Generated by Django 5.1.3 on 2024-12-03 00:11
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0176_repo_contributor_repo_contributor_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="badges/"),
        ),
        migrations.AlterField(
            model_name="ip",
            name="agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
