# Generated by Django 5.1.3 on 2024-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0176_merge_20241219_0544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="team_participants",
            field=models.ManyToManyField(blank=True, related_name="team_challenges", to="website.organization"),
        ),
    ]
