# Generated by Django 5.1.3 on 2024-12-29 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0176_repo_contributor_repo_contributor_count_and_more"),
        ("website", "0177_alter_challenge_team_participants"),
    ]

    operations = []
