# Generated by Django 5.1.4 on 2025-01-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0178_alter_ip_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="label",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "General"),
                    (1, "Number Error"),
                    (2, "Functional"),
                    (3, "Performance"),
                    (4, "Security"),
                    (5, "Typo"),
                    (6, "Design"),
                    (7, "Server Down"),
                    (8, "Trademark Squatting"),
                ],
                default=0,
            ),
        ),
    ]
