# Generated by Django 5.1.3 on 2025-01-10 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0179_contributorstats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repo",
            old_name="project_visit_count",
            new_name="repo_visit_count",
        ),
    ]

