# Generated by Django 5.1.4 on 2025-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0179_kudos"),
    ]

    operations = [
        migrations.AddField(
            model_name="kudos",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kudos",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
