# Generated by Django 5.1.4 on 2025-01-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0175_merge_20241219_1501"),
        ("website", "0179_contributorstats"),
    ]

    operations = []
