# Generated by Django 5.1.4 on 2025-01-08 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0178_merge_20241229_1948"),
        ("website", "0179_contributorstats"),
    ]

    operations = []

