# Generated by Django 5.1.4 on 2025-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0179_contributorstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slack",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
