# Generated by Django 5.1.3 on 2025-01-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0180_rename_project_visit_count_repo_repo_visit_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("service_name", models.CharField(max_length=100)),
                ("is_operational", models.BooleanField(default=False)),
                ("response_time", models.FloatField(null=True)),
                ("details", models.JSONField(default=dict)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["service_name", "timestamp"],
                        name="website_ser_service_78c797_idx",
                    )
                ],
            },
        ),
    ]
