# Generated by Django 5.1.4 on 2025-01-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0180_project_slack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slack",
            field=models.URLField(blank=True, null=True),
        ),
    ]
