# Generated by Django 5.1.4 on 2025-01-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0180_rename_project_visit_count_repo_repo_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slack_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
