# Generated by Django 5.1.4 on 2025-01-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0180_rename_project_visit_count_repo_repo_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="readme_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
