# Generated by Django 5.1.3 on 2025-01-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0180_rename_project_visit_count_repo_repo_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackintegration",
            name="welcome_message",
            field=models.TextField(
                blank=True,
                help_text="Custom welcome message for new members. Use Slack markdown formatting.",
                null=True,
            ),
        ),
    ]
