# Generated by Django 5.1.4 on 2025-01-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0179_alter_issue_label"),
        ("website", "0180_rename_project_visit_count_repo_repo_visit_count"),
    ]

    operations = []
