# Generated by Django 5.1.4 on 2025-01-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("website", "0181_alter_project_slack"),
        ("website", "0184_project_slack_channel_project_slack_id"),
    ]

    dependencies = [
        ("website", "0179_contributorstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slack",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slack_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slack_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
