# Generated by Django 5.1.4 on 2025-01-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0181_slackintegration_welcome_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("flagship", "Flagship"),
                    ("production", "Production"),
                    ("incubator", "Incubator"),
                    ("lab", "Lab"),
                    ("inactive", "Inactive"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]

