# Generated by Django 5.1.3 on 2025-01-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0182_project_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackBotActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workspace_id", models.CharField(max_length=20)),
                (
                    "workspace_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("team_join", "Team Join"),
                            ("command", "Slash Command"),
                            ("message", "Message"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=20, null=True)),
                ("details", models.JSONField(default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "activity_type"],
                        name="website_sla_workspa_1c714c_idx",
                    ),
                    models.Index(fields=["created"], name="website_sla_created_6b716d_idx"),
                ],
            },
        ),
    ]

