# Generated by Django 5.1.4 on 2025-01-24 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0180_merge_0178_merge_20241229_1948_0179_contributorstats"),
        ("website", "0182_project_status"),
    ]

    operations = []

