# Generated by Django 5.1.4 on 2025-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0182_merge_20250116_0944"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_channel", models.CharField(max_length=255)),
                ("slack_id", models.CharField(max_length=255, unique=True)),
                ("slack_url", models.URLField()),
            ],
        ),
    ]
