# Generated by Django 5.1.4 on 2025-01-25 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0181_repo_ai_summary_repo_readme_content"),
        ("website", "0182_project_status"),
    ]

    operations = []
