# Generated by Django 5.1.4 on 2025-01-26 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0183_merge_20250124_0618"),
        ("website", "0183_slackbotactivity"),
    ]

    operations = []
