# Generated by Django 5.1.4 on 2025-01-25 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0181_notification"),
        ("website", "0183_slackbotactivity"),
    ]

    operations = []
