# Generated by Django 5.1.4 on 2025-01-26 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0184_merge_0183_merge_20250124_0618_0183_slackbotactivity"),
        ("website", "0184_merge_20250125_2005"),
    ]

    operations = []
