# Generated by Django 5.1.4 on 2025-01-26 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0184_merge_0181_notification_0183_slackbotactivity"),
        ("website", "0185_merge_20250126_1451"),
    ]

    operations = []
