# Generated by Django 5.1.4 on 2025-01-26 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0185_merge_20250126_1451"),
        ("website", "0185_room"),
    ]

    operations = []
