# Generated by Django 5.1.4 on 2025-01-30 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0181_suggestion_organization"),
        ("website", "0186_userprofile_contribution_rank_and_more"),
    ]

    operations = []
