# Generated by Django 5.1.4 on 2025-01-30 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0186_merge_20250126_1739"),
        ("website", "0186_userprofile_contribution_rank_and_more"),
    ]

    operations = []
