# Generated by Django 5.1.4 on 2025-02-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0187_baconearning"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.IntegerField(unique=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("state", models.CharField(max_length=50)),
                ("submitted_at", models.DateTimeField()),
                ("url", models.URLField()),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="website.githubissue",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_made",
                        to="website.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenSourceRepo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("primary_language", models.CharField(max_length=50)),
                ("last_updated", models.DateTimeField()),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("last_pushed", models.DateTimeField()),
                ("license", models.CharField(blank=True, max_length=100)),
                (
                    "tags",
                    models.ManyToManyField(related_name="repositories", to="website.tag"),
                ),
            ],
        ),
    ]
