# Generated by Django 5.1.4 on 2025-02-01 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0187_baconearning"),
        ("website", "0187_merge_20250130_1313"),
    ]

    operations = []
