# Generated by Django 5.1.4 on 2025-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0188_kudos"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsshDiscussionChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(help_text="Source API (Discord, Slack etc)", max_length=100),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Server ID from the platform",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("invite_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="channels", to="website.tag"),
                ),
            ],
        ),
    ]
