# Generated by Django 5.1.4 on 2025-02-02 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0187_githubreview"),
        ("website", "0188_merge_0187_baconearning_0187_merge_20250130_1313"),
    ]

    operations = []
