# Generated by Django 5.1.4 on 2025-02-05 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0187_merge_20250130_1245"),
        ("website", "0188_kudos"),
    ]

    operations = []
