# Generated by Django 5.1.4 on 2025-01-30 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0181_alter_project_slack_squashed_0184_project_slack_channel_project_slack_id",
        ),
        ("website", "0186_userprofile_contribution_rank_and_more"),
    ]

    operations = []
