# Generated by Django 5.1.5 on 2025-02-09 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0186_merge_0185_merge_20250126_1451_0185_room"),
        ("website", "0188_kudos"),
    ]

    operations = []

