# Generated by Django 5.1.4 on 2025-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0189_repo_is_owasp_repo_alter_repo_contributor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsshArticles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("author_profile_image", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("publication_date", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        help_text="Source API (DEV Community, LinkedIn etc)",
                        max_length=255,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Server ID from the platform",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("cover_image", models.URLField(blank=True, null=True)),
                (
                    "reading_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="articles", to="website.tag"),
                ),
            ],
        ),
    ]
