# Generated by Django 5.1.5 on 2025-02-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0190_room_session_key_alter_room_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]

