# Generated by Django 5.1.4 on 2025-02-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0190_repo_is_owasp_repo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ossharticles",
            name="author_profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ossharticles",
            name="cover_image",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="ossharticles",
            name="url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
