# Generated by Django 5.1.4 on 2025-02-10 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0191_repo_is_owasp_repo_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OsshArticles",
            new_name="OsshArticle",
        ),
    ]
