# Generated by Django 5.1.5 on 2025-02-09 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0191_domain_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="integrations",
            field=models.ManyToManyField(blank=True, related_name="organizations", to="website.integration"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

