# Generated by Django 5.1.6 on 2025-02-14 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0183_merge_20250125_1053"),
        ("website", "0193_message"),
    ]

    operations = []
