# Generated by Django 5.1.6 on 2025-02-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0194_merge_0183_merge_20250125_1053_0193_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementCommandLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_name", models.CharField(max_length=255)),
                ("last_run", models.DateTimeField(auto_now=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "last_run",
            },
        ),
    ]

