# Generated by Django 5.1.6 on 2025-02-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0195_managementcommandlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementcommandlog",
            name="run_count",
            field=models.IntegerField(default=0),
        ),
    ]
