# Generated by Django 5.1.6 on 2025-02-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0196_managementcommandlog_run_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="closed_pull_requests",
            field=models.IntegerField(default=0),
        ),
    ]
