# Generated by Django 5.1.6 on 2025-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0197_repo_closed_pull_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubissue",
            name="issue_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
