# Generated by Django 5.1.6 on 2025-02-19 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0201_add_organization_address_and_coordinates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="repo",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repos",
                to="website.project",
            ),
        ),
    ]

