# Generated by Django 5.1.6 on 2025-02-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0202_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
