# Generated by Django 5.1.6 on 2025-02-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0204_ossharticle_osshcommunity_osshdiscussionchannel_and_more"),
        ("website", "0204_remove_organization_unique_organization_slug_and_more"),
    ]

    operations = []
