# Generated by Django 5.1.4 on 2025-02-21 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0204_ossharticle_osshcommunity_osshdiscussionchannel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="course_thumbnails/")),
                (
                    "level",
                    models.CharField(
                        choices=[("BEG", "Beginner"), ("INT", "Intermediate"), ("ADV", "Advanced")],
                        default="BEG",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video Lecture"),
                            ("LIVE", "Live Session"),
                            ("DOCUMENT", "Document"),
                            ("QUIZ", "Quiz"),
                        ],
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                ("scheduled_time", models.DateTimeField()),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, help_text="Duration in minutes", null=True)),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LectureStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(choices=[("PROGRESS", "In Progress"), ("COMPLETED", "Completed")], max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="organization",
            name="unique_organization_slug",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="domain_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="ip",
            name="ip_path_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issue_domain_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="org_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="repo",
            name="repo_project_idx",
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="courses_teaching", to="website.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="courses", to="website.tag"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="website.course"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="lectures", to="website.tag"),
        ),
        migrations.AddField(
            model_name="lecturestatus",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lecture_status", to="website.lecture"
            ),
        ),
        migrations.AddField(
            model_name="lecturestatus",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="student", to="website.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="website.course"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.userprofile"),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="website.course",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="website.section",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
