# Generated by Django 5.1.4 on 2025-02-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0205_course_enrollment_lecture_lecturestatus_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lecture",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="website.course"
            ),
        ),
    ]
