# Generated by Django 5.1.5 on 2025-02-25 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0208_alter_points_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="osshdiscussionchannel",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="category",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="contributors_count",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="description",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="name",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="source",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="osshcommunity",
            name="website",
        ),
        migrations.RemoveField(
            model_name="repo",
            name="is_owasp_repo",
        ),
        migrations.DeleteModel(
            name="OsshArticle",
        ),
        migrations.DeleteModel(
            name="OsshDiscussionChannel",
        ),
    ]
