# Generated by Django 5.1.6 on 2025-02-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0208_alter_points_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repos",
                to="website.organization",
            ),
        ),
    ]

