# Generated by Django 5.1.4 on 2025-02-23 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0206_alter_lecture_content_alter_lecture_scheduled_time_and_more"),
        ("website", "0208_alter_points_created"),
    ]

    operations = []
