# Generated by Django 3.2.7 on 2023-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0208_auto_20230915_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_signups',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
