# Generated by Django 5.1.5 on 2025-02-26 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0209_baconsubmission"),
        ("website", "0209_repo_organization"),
    ]

    operations = []
