# Generated by Django 5.1.5 on 2025-02-27 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0209_remove_osshdiscussionchannel_tags_and_more"),
        ("website", "0209_repo_organization"),
    ]

    operations = []
