# Generated by Django 5.1.4 on 2025-02-26 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0209_merge_20250223_1248"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(fields=["organization"], name="domain_org_idx"),
        ),
        migrations.AddIndex(
            model_name="ip",
            index=models.Index(fields=["path", "created"], name="ip_path_created_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["domain", "status"], name="issue_domain_status_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["created"], name="org_created_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["organization"], name="project_org_idx"),
        ),
        migrations.AddIndex(
            model_name="repo",
            index=models.Index(fields=["project"], name="repo_project_idx"),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(fields=("slug",), name="unique_organization_slug"),
        ),
    ]
