# Generated by Django 5.1.6 on 2025-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0210_merge_0209_baconsubmission_0209_repo_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubreview",
            name="review_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
