# Generated by Django 5.1.6 on 2025-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0210_merge_0209_baconsubmission_0209_repo_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="github_comments_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="github_issue_state",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
