# Generated by Django 5.1.4 on 2025-02-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0211_alter_lecturestatus_lecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="website.userprofile"
            ),
        ),
    ]
