# Generated by Django 5.1.6 on 2025-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0213_organization_categories_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Statistic",
                "verbose_name_plural": "Daily Statistics",
                "ordering": ["-modified"],
            },
        ),
    ]

