# Generated by Django 5.1.6 on 2025-03-02 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0215_bid_github_username_alter_bid_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="bch_tx_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="githubissue",
            name="p2p_amount_bch",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="githubissue",
            name="p2p_amount_usd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="githubissue",
            name="p2p_payment_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubissue",
            name="sent_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="github_issue_p2p_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bch_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, validators=[website.models.validate_bch_address]
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bch_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, validators=[website.models.validate_bch_address]
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="btc_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, validators=[website.models.validate_btc_address]
            ),
        ),
    ]
