# Generated by Django 5.1.6 on 2025-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0216_githubissue_bch_tx_id_githubissue_p2p_amount_bch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="discord_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="element_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="gitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="matrix_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="slack_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="zulipchat_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]

