# Generated by Django 5.1.6 on 2025-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0218_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="repos_updated_at",
            field=models.DateTimeField(blank=True, help_text="When repositories were last updated", null=True),
        ),
    ]

