# Generated by Django 5.1.6 on 2025-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0219_organization_repos_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystats",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="issue",
            name="label",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "General"),
                    (1, "Number Error"),
                    (2, "Functional"),
                    (3, "Performance"),
                    (4, "Security"),
                    (5, "Typo"),
                    (6, "Design"),
                    (7, "Server Down"),
                    (8, "Trademark Squatting"),
                ],
                default=0,
            ),
        ),
    ]

