# Generated by Django 5.1.7 on 2025-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0221_userprofile_public_key_alter_message_room_thread_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
