# Generated by Django 5.1.7 on 2025-03-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0221_userprofile_public_key_alter_message_room_thread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="daily_visit_count",
            field=models.PositiveIntegerField(default=0, help_text="Count of days visited"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_visit_day",
            field=models.DateField(blank=True, help_text="Last day the user visited", null=True),
        ),
    ]

