# Generated by Django 5.1.6 on 2025-03-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0222_userprofile_daily_visit_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="has_dollar_tag",
            field=models.BooleanField(default=False),
        ),
    ]

