# Generated by Django 5.1.6 on 2025-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0225_hackathon_hackathonsponsor_hackathonprize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="last_pr_fetch_date",
            field=models.DateTimeField(blank=True, help_text="When PRs were last fetched", null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="last_pr_page_processed",
            field=models.IntegerField(default=0, help_text="Last page of PRs processed from GitHub API"),
        ),
    ]

