# Generated by Django 5.1.6 on 2025-03-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0226_repo_last_pr_fetch_date_repo_last_pr_page_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubissue",
            name="issue_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="githubissue",
            unique_together={("issue_id", "repo")},
        ),
    ]
