# Generated by Django 5.1.6 on 2025-03-11 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0227_alter_githubissue_issue_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="github_issues",
                to="website.contributor",
            ),
        ),
    ]

