# Generated by Django 5.1.6 on 2025-03-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0228_githubissue_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="sponsor_link",
            field=models.URLField(blank=True, help_text="Link to sponsorship information or application", null=True),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="sponsor_note",
            field=models.TextField(
                blank=True, help_text="Additional information about sponsorship opportunities", null=True
            ),
        ),
    ]

