# Generated by Django 5.1.7 on 2025-03-15 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0231_newsletter_newslettersubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="token_created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Timestamp when confirmation token was created"
            ),
        ),
    ]
