# Generated by Django 5.1.7 on 2025-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0232_bannedapp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repo",
            options={"verbose_name_plural": "Repositories"},
        ),
        migrations.RemoveField(
            model_name="repo",
            name="size",
        ),
        migrations.AddField(
            model_name="repo",
            name="code_coverage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="code_quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="discussions_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="last_downloads_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="last_github_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="last_quality_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="last_social_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="latest_release",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="latest_release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="linkedin_mentions",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="maintainability_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="merged_pull_requests",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="package_downloads",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="pull_requests",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="recent_commits",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="recent_discussions",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="recent_package_downloads",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="releases_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="twitter_mentions",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="vulnerabilities",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
