# Generated by Django 5.1.7 on 2025-03-19 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0232_bannedapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="github_issues_assignee",
                to="website.contributor",
            ),
        ),
    ]
