# Generated by Django 5.1.7 on 2025-03-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0233_githubissue_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="linked_pull_requests",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "pull_request"},
                related_name="linked_issues",
                to="website.githubissue",
            ),
        ),
    ]
