# Generated by Django 5.1.7 on 2025-03-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0234_githubissue_linked_pull_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="instructor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="website.userprofile"
            ),
        ),
    ]
