# Generated by Django 5.1.7 on 2025-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0235_alter_lecture_content_alter_lecture_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="message",
            field=models.CharField(help_text="Message limited to 280 characters", max_length=280),
        ),
    ]
