# Generated by Django 5.1.7 on 2025-04-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0235_alter_lecture_content_alter_lecture_instructor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="instructor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="website.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="ReminderSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reminder_time", models.TimeField(help_text="Time to send daily reminders (in user's timezone)")),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("is_active", models.BooleanField(default=True, help_text="Enable/disable daily reminders")),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reminder_time_utc",
                    models.TimeField(blank=True, help_text="Time to send daily reminders (in UTC)", null=True),
                ),
            ],
            options={
                "verbose_name": "Reminder Settings",
                "verbose_name_plural": "Reminder Settings",
                "indexes": [
                    models.Index(fields=["is_active"], name="website_rem_is_acti_d29d2c_idx"),
                    models.Index(fields=["reminder_time_utc"], name="website_rem_reminde_fc3689_idx"),
                ],
            },
        ),
    ]
