# Generated by Django 5.1.7 on 2025-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0236_alter_queue_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reactions",
            field=models.JSONField(default=dict, help_text="Stores emoji reactions and their counts"),
        ),
    ]
