# Generated by Django 5.1.8 on 2025-05-12 13:30

from django.db import migrations


def remove_first_suggestion_badge(apps, schema_editor):
    Badge = apps.get_model("website", "Badge")
    badge_title = "First Suggestion"
    Badge.objects.filter(title=badge_title).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0238_add_reminder_settings"),
    ]

    operations = [
        migrations.RunPython(remove_first_suggestion_badge),
    ]
