# Generated by Django 5.1.7 on 2025-05-04 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0238_add_reminder_settings"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE auth_user SET email = username || '@placeholder.com' WHERE email IS NULL OR email = '';",
            # This is the reverse SQL if you need to roll back
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'auth_user_email_unique'
                ) THEN
                    ALTER TABLE auth_user ADD CONSTRAINT auth_user_email_unique UNIQUE (email);
                END IF;
            END
            $$;
            """,
            "ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS auth_user_email_unique;",
        ),
    ]
