# Generated by Django 5.1.7 on 2025-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0240_add_first_forum_post_badge_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="has_security_txt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="domain",
            name="security_txt_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
