# Generated by Django 5.1.7 on 2025-05-04 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0241_domain_has_security_txt_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE auth_user SET email = username || '@placeholder.com' WHERE email IS NULL OR email = '';",
            # This is the reverse SQL if you need to roll back
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            # Add uniqueness constraint
            "ALTER TABLE auth_user ADD CONSTRAINT auth_user_email_unique UNIQUE (email);",
            # Reverse operation
            "ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS auth_user_email_unique;",
        ),
    ]
