# Generated by Django 5.1.8 on 2025-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0241_domain_has_security_txt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labs",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("estimated_time", models.PositiveIntegerField(help_text="Estimated time in minutes")),
                ("total_tasks", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lab",
                "verbose_name_plural": "Labs",
                "ordering": ["order"],
            },
        ),
    ]
