# Generated by Django 5.1.8 on 2025-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0242_githubinstallation_githubapprepo_aibotcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubinstallation",
            name="id",
        ),
        migrations.AddField(
            model_name="aibotcomment",
            name="comment_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="githubapprepo",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="githubinstallation",
            name="installation_id",
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name="githubapprepo",
            constraint=models.UniqueConstraint(fields=("installation", "repo_id"), name="unique_installation_repo"),
        ),
    ]
