# Generated by Django 5.1.8 on 2025-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0242_labs"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="bacon_reward",
            field=models.IntegerField(default=5),
        ),
    ]
