# Generated by Django 5.1.8 on 2025-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0243_remove_githubinstallation_id_aibotcomment_comment_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GithubInstallation",
            new_name="GithubAppInstallation",
        ),
        migrations.AddField(
            model_name="githubapprepo",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("removed", "Removed"),
                    ("pending", "Pending"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
