# Generated by Django 5.1.8 on 2025-07-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0243_add_bacon_rewards_to_challenges"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "task_type",
                    models.CharField(choices=[("theory", "Theory"), ("simulation", "Simulation")], max_length=20),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="website.labs"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["lab", "order"],
                "unique_together": {("lab", "order")},
            },
        ),
        migrations.CreateModel(
            name="TaskContent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theory_content", models.TextField(blank=True)),
                ("mcq_question", models.TextField(blank=True)),
                ("mcq_options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.CharField(blank=True, max_length=10)),
                ("simulation_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content", to="website.tasks"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Content",
                "verbose_name_plural": "Task Contents",
            },
        ),
    ]
