# Generated by Django 5.1.8 on 2025-07-28 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0243_add_bacon_rewards_to_challenges"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StakingPool",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("head_to_head", "Head to Head (2 players)"),
                            ("triple_threat", "Triple Threat (3 players)"),
                        ],
                        default="head_to_head",
                        max_length=20,
                    ),
                ),
                (
                    "stake_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Fixed amount each player must stake", max_digits=10
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Players"),
                            ("full", "Full - Ready to Start"),
                            ("active", "Challenge Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staking_pools",
                        to="website.challenge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_staking_pools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_staking_pools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staking Pool",
                "verbose_name_plural": "Staking Pools",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StakingTransaction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("stake", "Stake - Joined Pool"),
                            ("win", "Win - Won Pool"),
                            ("refund", "Refund - Pool Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="website.stakingpool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staking_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staking Transaction",
                "verbose_name_plural": "Staking Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StakingEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("staked_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("actual_reward", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - In Competition"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("refunded", "Refunded"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("challenge_completed", models.BooleanField(default=False)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staking_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="website.stakingpool"
                    ),
                ),
            ],
            options={
                "verbose_name": "Staking Entry",
                "verbose_name_plural": "Staking Entries",
                "ordering": ["-created_at"],
                "unique_together": {("user", "pool")},
            },
        ),
    ]
