# Generated by Django 5.1.8 on 2025-08-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0244_rename_githubinstallation_githubappinstallation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="githubappinstallation",
            old_name="events",
            new_name="subscribed_events",
        ),
        migrations.RemoveField(
            model_name="githubappinstallation",
            name="is_active",
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="activated_by_account_login",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="removed_by_account_login",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="state",
            field=models.CharField(
                choices=[("active", "Active"), ("removed", "Removed"), ("suspended", "Suspended")],
                default="active",
                max_length=20,
            ),
        ),
    ]
