# Generated by Django 5.1.8 on 2025-08-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0244_stakingpool_stakingtransaction_stakingentry"),
        ("website", "0244_tasks_taskcontent"),
    ]

    operations = []
