# Generated by Django 5.1.8 on 2025-07-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0179_update_challenge_bacon_rewards"),
        ("website", "0244_update_existing_challenges_bacon_rewards"),
    ]

    operations = []
