# Generated by Django 5.1.8 on 2025-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0245_rename_events_githubappinstallation_subscribed_events_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapprepo",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("removed", "Removed"),
                    ("processing", "Processing"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
