# Generated by Django 5.1.8 on 2025-11-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment_id", models.BigIntegerField(unique=True)),
                ("commenter_login", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("comment_url", models.URLField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "commenter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_comments",
                        to="website.contributor",
                    ),
                ),
                (
                    "commenter_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_comments",
                        to="website.userprofile",
                    ),
                ),
                (
                    "github_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_comments",
                        to="website.githubissue",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="github_comments", to="website.repo"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["repo", "commenter_login"], name="website_git_repo_id_cdff16_idx"),
                    models.Index(fields=["commenter_login"], name="website_git_comment_c88653_idx"),
                ],
            },
        ),
    ]
