# Generated by Django 5.1.8 on 2025-11-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0246_add_user_progress_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Job title", max_length=255)),
                ("description", models.TextField(help_text="Detailed job description with responsibilities")),
                (
                    "requirements",
                    models.TextField(blank=True, help_text="Job requirements or qualifications", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Job location (city, remote, hybrid)", max_length=255, null=True
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full Time"),
                            ("part-time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full-time",
                        help_text="Type of employment",
                        max_length=20,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, help_text="Salary range (e.g., $50k-$70k, Competitive)", max_length=100, null=True
                    ),
                ),
                ("is_public", models.BooleanField(default=True, help_text="Whether this job is publicly visible")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("paused", "Paused"), ("closed", "Closed")],
                        default="draft",
                        help_text="Current status of the job posting",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time when this job posting expires", null=True
                    ),
                ),
                (
                    "application_email",
                    models.EmailField(blank=True, help_text="Email to receive applications", max_length=254, null=True),
                ),
                (
                    "application_url",
                    models.URLField(blank=True, help_text="URL to external application page", null=True),
                ),
                (
                    "application_instructions",
                    models.TextField(blank=True, help_text="Custom instructions for how to apply", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views_count", models.IntegerField(default=0, help_text="Number of times this job has been viewed")),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization posting the job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="website.organization",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this job posting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "is_public", "status"], name="job_org_pub_status_idx"),
                    models.Index(fields=["is_public", "status"], name="job_public_status_idx"),
                    models.Index(fields=["-created_at"], name="job_created_idx"),
                ],
            },
        ),
    ]
