# Generated by Django 5.1.8 on 2025-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slack",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slack_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slack_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
