# Generated by Django 5.1.8 on 2025-08-31 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubAppInstallation",
            fields=[
                ("installation_id", models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ("app_id", models.BigIntegerField()),
                ("app_name", models.CharField(max_length=100)),
                ("account_login", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(choices=[("User", "User"), ("Organization", "Organization")], max_length=12),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_by_account_login", models.CharField(blank=True, max_length=100, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_by_account_login", models.CharField(blank=True, max_length=100, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_by_account_login", models.CharField(blank=True, max_length=100, null=True)),
                ("permissions", models.JSONField(default=dict, help_text="Permissions granted to this installation")),
                ("subscribed_events", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GithubAppRepo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("removed", "Removed"),
                            ("processing", "Processing"),
                            ("error", "Error"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                            ("suspended", "Suspended"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("permissions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="website.githubappinstallation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AibotComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_number", models.BigIntegerField(help_text="Issue or PR number on GitHub")),
                ("comment_id", models.BigIntegerField(blank=True, null=True)),
                ("comment_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "comment_action",
                    models.CharField(
                        choices=[("posted", "Posted"), ("patched", "Patched")], default="posted", max_length=10
                    ),
                ),
                ("revision", models.IntegerField(default=1)),
                (
                    "trigger_event",
                    models.CharField(
                        db_index=True, help_text="e.g., 'issue_comment.created', 'pull_request.opened'", max_length=50
                    ),
                ),
                (
                    "triggered_by_username",
                    models.CharField(help_text="GitHub user who triggered the bot", max_length=100),
                ),
                ("trigger_comment_body", models.TextField(blank=True, null=True)),
                ("prompt", models.TextField(help_text="Full prompt sent to LLM")),
                ("response", models.TextField(help_text="AI-generated response")),
                ("model_used", models.CharField(default="gemini-2.0-flash", max_length=50)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Estimated cost of this LLM call",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        help_text="The GitHub App installation that triggered this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aibot_comments",
                        to="website.githubappinstallation",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="The repo where the comment was made",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aibot_comments",
                        to="website.githubapprepo",
                    ),
                ),
            ],
        ),
    ]
