# Generated by Django 5.1.8 on 2025-08-30 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0242_githubappinstallation_githubapprepo_aibotcomment"),
        ("website", "0246_add_user_progress_models"),
    ]

    operations = []
