# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slack_user_id",
            field=models.CharField(
                blank=True, help_text="Slack user ID for DM reminders", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="remindersettings",
            name="slack_notifications_enabled",
            field=models.BooleanField(default=False, help_text="Enable Slack DM notifications for daily reminders"),
        ),
    ]
