# Generated by Django 5.1.8 on 2025-11-15 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystatusreport",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_status_reports",
                to="website.organization",
            ),
        ),
    ]
