# Generated by Django 5.0.7 on 2025-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, help_text="Optional description of what this tag represents"),
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ('general', 'General'),
                    ('security', 'Security'),
                    ('performance', 'Performance'),
                    ('ui_ux', 'UI/UX'),
                    ('bug', 'Bug'),  
                    ('feature', 'Feature'),
                    ('documentation', 'Documentation'),
                    ('infrastructure', 'Infrastructure'),
                    ('testing', 'Testing'),
                    ('data', 'Data'),
                ],
                default='general',
                max_length=20,
                help_text="Category to organize related tags"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ('#e74c3c', 'Red'),  # BLT's primary red
                    ('#3498db', 'Blue'),
                    ('#2ecc71', 'Green'),
                    ('#f39c12', 'Orange'),
                    ('#9b59b6', 'Purple'),
                    ('#1abc9c', 'Teal'),
                    ('#34495e', 'Dark Gray'),
                    ('#e67e22', 'Dark Orange'),
                    ('#95a5a6', 'Gray'),
                    ('#f1c40f', 'Yellow'),
                ],
                default='#e74c3c',
                max_length=7,
                help_text="Display color for the tag"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.CharField(blank=True, max_length=50, help_text="FontAwesome icon class (e.g., 'fas fa-bug')"),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this tag is active and can be used"),
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]