# Generated by Django 5.1.8 on 2025-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0246_add_user_progress_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="github_org",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                help_text="GitHub organization name",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="gsoc_years",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                help_text="Comma-separated list of years participated in Google Summer of Code (e.g., '2024,2023,2022')",
            ),
        ),
    ]
