# Generated by Django 5.1.8 on 2025-08-10 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0246_alter_githubapprepo_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubapprepo",
            name="is_active",
        ),
    ]
