# Generated by - Django 5.1.8 on 2025-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0247_organization_github_org_gsoc_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementcommandlog",
            name="execution_time",
            field=models.FloatField(blank=True, help_text="Execution time in seconds", null=True),
        ),
        migrations.AddField(
            model_name="managementcommandlog",
            name="file_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managementcommandlog",
            name="file_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="managementcommandlog",
            name="github_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="managementcommandlog",
            name="output",
            field=models.TextField(blank=True, help_text="Command execution output", null=True),
        ),
    ]
