# Generated by Django 5.1.8 on 2025-08-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0247_remove_githubapprepo_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubapprepo",
            name="url",
        ),
        migrations.AlterField(
            model_name="aibotcomment",
            name="installation",
            field=models.ForeignKey(
                help_text="The GitHub App installation that triggered this",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aibot_comments",
                to="website.githubappinstallation",
            ),
        ),
        migrations.AlterField(
            model_name="aibotcomment",
            name="repository",
            field=models.ForeignKey(
                help_text="The repo where the comment was made",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aibot_comments",
                to="website.githubapprepo",
            ),
        ),
        migrations.AlterField(
            model_name="githubapprepo",
            name="repo_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
