# Generated by Django 5.1.8 on 2025-08-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0247_merge_20250830_1938"),
    ]

    operations = [
        migrations.AddField(
            model_name="aibotcomment",
            name="comment_action",
            field=models.CharField(
                choices=[("posted", "Posted"), ("patched", "Patched")], default="posted", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="aibotcomment",
            name="revision",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="aibotcomment",
            name="comment_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aibotcomment",
            name="installation",
            field=models.ForeignKey(
                help_text="The GitHub App installation that triggered this",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aibot_comments",
                to="website.githubappinstallation",
            ),
        ),
    ]
