# Generated by Django 5.1.8 on 2025-08-10 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0248_remove_githubapprepo_url_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="githubapprepo",
            name="unique_installation_repo",
        ),
    ]
