# Generated by Django 5.1.8 on 2025-11-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0248_add_slack_fields_to_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to="website.organization",
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to="website.project",
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="repo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to="website.repo",
            ),
        ),
    ]
