# Generated by Django 5.1.8 on 2025-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0248_add_slack_fields_to_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="spam_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="spam_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
