# Generated by Django 5.1.8 on 2025-11-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0248_add_slack_fields_to_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["delivery_id"], name="website_web_deliver_79ecfb_idx")],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pr_number", models.IntegerField()),
                ("currency", models.CharField(max_length=10)),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tx_id", models.CharField(blank=True, max_length=256, null=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("repo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.repo")),
            ],
            options={
                "indexes": [models.Index(fields=["repo", "pr_number"], name="website_pay_repo_id_b34792_idx")],
                "unique_together": {("repo", "pr_number", "currency")},
            },
        ),
    ]
