# Generated by Django 5.1.8 on 2025-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0248_add_slack_fields_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="project_logos"),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
