# Generated by Django 5.1.8 on 2025-11-22 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0247_job"),
        ("website", "0248_add_slack_fields_to_project"),
    ]

    operations = []
