# Generated by Django 5.1.8 on 2025-11-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0247_job"),
        ("website", "0249_alter_organization_logo_alter_organization_url_and_more"),
    ]

    operations = []
