# Generated by Django 5.1.8 on 2025-08-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0249_remove_githubapprepo_unique_installation_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aibotcomment",
            name="installation",
            field=models.ForeignKey(
                help_text="The GitHub App installation that triggered this",
                null=True,
                on_delete=django.db.models.deletion.SET,
                related_name="aibot_comments",
                to="website.githubappinstallation",
            ),
        ),
        migrations.AlterField(
            model_name="aibotcomment",
            name="repository",
            field=models.ForeignKey(
                help_text="The repo where the comment was made",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aibot_comments",
                to="website.githubapprepo",
            ),
        ),
        migrations.AlterField(
            model_name="githubapprepo",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("removed", "Removed"),
                    ("processing", "Processing"),
                    ("error", "Error"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
