# Generated by Django 5.1.8 on 2025-11-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0249_webhookevent_paymentrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="user_profile",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="website.userprofile"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrecord",
            index=models.Index(fields=["user_profile"], name="website_pay_user_pr_6b7a2e_idx"),
        ),
    ]
