# Generated by Django 5.1.8 on 2025-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0249_merge_0247_job_0248_add_slack_fields_to_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_clicks",
            field=models.JSONField(default=dict, help_text="Track social media profile visits"),
        ),
    ]
