# Generated by Django manually
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0249_merge_0247_job_0248_add_slack_fields_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_club_member',
            field=models.BooleanField(default=False, help_text='Has at least 1 merged PR per week'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_club_member',
            field=models.BooleanField(default=False, help_text='Has at least 1 merged PR per month'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ten_club_member',
            field=models.BooleanField(default=False, help_text='Has 10+ merged PRs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fifty_club_member',
            field=models.BooleanField(default=False, help_text='Has 50+ merged PRs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hundred_club_member',
            field=models.BooleanField(default=False, help_text='Has 100+ merged PRs'),
        ),
    ]