# Generated by Django 5.1.8 on 2025-11-20 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0249_alter_project_logo_alter_project_url"),
    ]

    operations = []
