# Generated by Django 5.1.8 on 2025-11-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0250_auto_20251120_1758"),
    ]

    operations = []
