# Generated by Django 5.1.8 on 2025-11-23 04:11

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0250_enhanced_bidding_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="repoowner",
            name="bch_address",
            field=models.CharField(
                blank=True,
                help_text="Public BCH address for funding accepted bids",
                max_length=100,
                null=True,
                validators=[website.models.validate_bch_address],
            ),
        ),
    ]
