# Generated by Django 5.1.8 on 2025-11-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0250_paymentrecord_user_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pr_number", models.IntegerField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="website.repo"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="website.userprofile"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user_profile"], name="website_sus_user_pr_8bd2ed_idx"),
                    models.Index(fields=["repo"], name="website_sus_repo_id_c352d9_idx"),
                    models.Index(fields=["event_type"], name="website_sus_event_t_0adf5b_idx"),
                ],
            },
        ),
    ]
