# Generated by Django 5.1.8 on 2025-11-16 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0251_add_fields_to_management_command_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adventure",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("owasp_security", "OWASP Security"), ("open_source", "Open Source Contribution")],
                        default="owasp_security",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("badge_emoji", models.CharField(default="🏆", help_text="Emoji icon for the badge", max_length=10)),
                ("badge_title", models.CharField(help_text="Badge title to be awarded", max_length=100)),
                ("estimated_time", models.CharField(blank=True, help_text="e.g., '2-3 hours'", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adventures",
                        to="website.badge",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="AdventureTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0, help_text="Order in which the task appears")),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Whether this task is required to complete the adventure"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="website.adventure"
                    ),
                ),
            ],
            options={
                "ordering": ["adventure", "order"],
                "unique_together": {("adventure", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserAdventureProgress",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="website.adventure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adventure_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User adventure progress",
                "unique_together": {("user", "adventure")},
            },
        ),
        migrations.CreateModel(
            name="UserTaskSubmission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "proof_url",
                    models.URLField(blank=True, help_text="Link to pull request, issue, blog post, or other evidence"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes or explanation")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending Review"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("reviewer_notes", models.TextField(blank=True, help_text="Feedback from reviewer")),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_submissions",
                        to="website.useradventureprogress",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_task_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="website.adventuretask",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("progress", "task")},
            },
        ),
    ]
