# Generated by Django 5.1.8 on 2025-11-23 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0250_add_forumpost_links"),
        ("website", "0251_add_fields_to_management_command_log"),
    ]

    operations = []
