# Generated by Django 5.1.8 on 2025-11-23 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import website.models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0251_add_fields_to_management_command_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Bid model enhancements
        migrations.AddField(
            model_name="bid",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="dynamic_image_token",
            field=models.CharField(blank=True, help_text="Unique token for dynamic image", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="escrow_address",
            field=models.CharField(blank=True, help_text="Generated BCH address for escrow", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="funded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="funding_tx_hash",
            field=models.CharField(
                blank=True, help_text="Transaction hash when repo owner funds the bid", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="pr_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="release_tx_hash",
            field=models.CharField(
                blank=True, help_text="Transaction hash when funds are released to coder", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="review_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Accepted", "Accepted"),
                    ("Funded", "Funded"),
                    ("InProgress", "In Progress"),
                    ("Submitted", "Submitted"),
                    ("Completed", "Completed"),
                    ("Disputed", "Disputed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Open",
                max_length=15,
            ),
        ),
        # BidTransaction model
        migrations.CreateModel(
            name="BidTransaction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("funding", "Funding"), ("release", "Release"), ("refund", "Refund")], max_length=10
                    ),
                ),
                ("tx_hash", models.CharField(max_length=64, unique=True)),
                ("from_address", models.CharField(max_length=100)),
                ("to_address", models.CharField(max_length=100)),
                ("amount_bch", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("failed", "Failed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("confirmations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="website.bid"
                    ),
                ),
            ],
        ),
        # RepoOwner model with bch_address field
        migrations.CreateModel(
            name="RepoOwner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("github_username", models.CharField(max_length=100)),
                (
                    "verified_repos",
                    models.JSONField(default=list, help_text="List of repository URLs this owner has access to"),
                ),
                (
                    "bch_address",
                    models.CharField(
                        blank=True,
                        help_text="Public BCH address for funding accepted bids",
                        max_length=100,
                        null=True,
                        validators=[website.models.validate_bch_address],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
