# Generated by Django 5.1.8 on 2025-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0251_suspiciousevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField(default=dict)),
            ],
        ),
    ]
