# Generated by Django 5.1.8 on 2025-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0251_auto_20251120_1806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="organization_logos", max_length=255),
        ),
    ]
