# Generated by Django 5.1.8 on 2025-11-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0252_add_adventure_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamDetection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_type", models.CharField(choices=[("issue", "Issue"), ("comment", "Comment")], max_length=20)),
                ("content_id", models.PositiveIntegerField(blank=True, null=True)),
                ("text_content", models.TextField(help_text="The content that was flagged as spam")),
                ("detection_reason", models.TextField(help_text="LLM reasoning for spam detection")),
                (
                    "confidence_score",
                    models.FloatField(blank=True, help_text="Confidence score from 0 to 1", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected as Spam"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spam_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_flagged_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Spam Detection",
                "verbose_name_plural": "Spam Detections",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status", "created_at"], name="spam_status_created_idx")],
            },
        ),
    ]
