# Generated by Django 5.1.8 on 2025-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trademark",
            options={"ordering": ["-filing_date"]},
        ),
        migrations.AlterField(
            model_name="trademark",
            name="filing_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="keyword",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="registration_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="serial_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="trademark",
            index=models.Index(fields=["keyword", "status_code"], name="website_tra_keyword_322648_idx"),
        ),
        migrations.AddIndex(
            model_name="trademark",
            index=models.Index(fields=["registration_number", "serial_number"], name="website_tra_registr_51069f_idx"),
        ),
        migrations.AddIndex(
            model_name="trademark",
            index=models.Index(fields=["filing_date"], name="website_tra_filing__73c467_idx"),
        ),
    ]
