# Generated by Django 5.1.8 on 2025-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="anonymous_creator_email",
            field=models.EmailField(
                blank=True, help_text="Email of anonymous creator for notifications", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="hunt",
            name="is_anonymous",
            field=models.BooleanField(default=False, help_text="Whether this hunt was created anonymously"),
        ),
        migrations.AddField(
            model_name="hunt",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount paid upfront for anonymous hunt",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hunt",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed"), ("refunded", "Refunded")],
                default="pending",
                help_text="Status of upfront payment for anonymous hunts",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hunt",
            name="requires_bug_verification",
            field=models.BooleanField(default=True, help_text="Whether bugs need verification before payout"),
        ),
    ]
