# Generated by Django 5.1.8 on 2025-11-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0252_fix_organization_logo_field_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="url",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
