# Generated by Django 5.1.8 on 2025-11-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verifier",
            field=models.BooleanField(default=False, help_text="Whether the user has verifier permissions"),
        ),
    ]
