# Generated by Django 5.1.8 on 2025-11-23 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackHuddle",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator_id", models.CharField(max_length=255)),
                ("workspace_id", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("message_ts", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slack Huddle",
                "verbose_name_plural": "Slack Huddles",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(fields=["workspace_id", "status"], name="website_sla_workspa_196b8b_idx"),
                    models.Index(fields=["channel_id", "scheduled_at"], name="website_sla_channel_2d28f9_idx"),
                    models.Index(fields=["creator_id"], name="website_sla_creator_7ec128_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackPoll",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator_id", models.CharField(max_length=255)),
                ("workspace_id", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
                ("message_ts", models.CharField(blank=True, max_length=255, null=True)),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")], default="active", max_length=20
                    ),
                ),
                ("allow_multiple_votes", models.BooleanField(default=False)),
                ("anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Slack Poll",
                "verbose_name_plural": "Slack Polls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["workspace_id", "status"], name="website_sla_workspa_3ca63e_idx"),
                    models.Index(fields=["creator_id"], name="website_sla_creator_e7612b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackPollOption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("option_text", models.CharField(max_length=255)),
                ("option_number", models.IntegerField()),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="website.slackpoll"
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Poll Option",
                "verbose_name_plural": "Slack Poll Options",
                "ordering": ["option_number"],
                "unique_together": {("poll", "option_number")},
            },
        ),
        migrations.CreateModel(
            name="SlackReminder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator_id", models.CharField(max_length=255)),
                ("workspace_id", models.CharField(max_length=255)),
                (
                    "target_type",
                    models.CharField(choices=[("user", "User"), ("channel", "Channel")], default="user", max_length=20),
                ),
                ("target_id", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("remind_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Slack Reminder",
                "verbose_name_plural": "Slack Reminders",
                "ordering": ["remind_at"],
                "indexes": [
                    models.Index(fields=["workspace_id", "status", "remind_at"], name="website_sla_workspa_692f73_idx"),
                    models.Index(fields=["creator_id"], name="website_sla_creator_09d1fe_idx"),
                    models.Index(fields=["target_id"], name="website_sla_target__d6c74c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackHuddleParticipant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=255)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("maybe", "Maybe"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "huddle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="website.slackhuddle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Huddle Participant",
                "verbose_name_plural": "Slack Huddle Participants",
                "unique_together": {("huddle", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="SlackPollVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voter_id", models.CharField(max_length=255)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="website.slackpolloption"
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="website.slackpoll"
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Poll Vote",
                "verbose_name_plural": "Slack Poll Votes",
                "indexes": [models.Index(fields=["poll", "voter_id"], name="website_sla_poll_id_e2f088_idx")],
                "unique_together": {("poll", "voter_id", "option")},
            },
        ),
    ]
