# Generated by Django 5.1.8 on 2025-11-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of what this tag represents", null=True
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Optional category to group related tags (e.g., 'security', 'feature', 'bug')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Hex color code for tag display (e.g., '#e74c3c')",
                max_length=7,
                null=True,
            ),
        ),
    ]
