# Generated by Django 5.1.8 on 2025-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="private_reports_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
