# Generated by Django 5.1.8 on 2025-11-20 04:49

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0252_globalconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="allowed_autopay_labels",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="repo",
            name="autopay_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="max_payout_usd",
            field=models.DecimalField(decimal_places=2, default=Decimal("100"), max_digits=12),
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pr_number", models.IntegerField()),
                ("bounty_issue_number", models.IntegerField(blank=True, null=True)),
                ("tx_id", models.CharField(max_length=256)),
                ("currency", models.CharField(max_length=10)),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bch_amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("usd_rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("pr_payload", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="receipt", to="website.paymentrecord"
                    ),
                ),
                ("repo", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="website.repo")),
                (
                    "user_profile",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="website.userprofile"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["repo"], name="website_pay_repo_id_acee40_idx"),
                    models.Index(fields=["user_profile"], name="website_pay_user_pr_bf0658_idx"),
                    models.Index(fields=["pr_number"], name="website_pay_pr_numb_800efd_idx"),
                    models.Index(fields=["tx_id"], name="website_pay_tx_id_52deb0_idx"),
                ],
            },
        ),
    ]
