# Generated by Django 5.1.3 on 2025-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackintegration",
            name="weekly_report_channel_name",
            field=models.CharField(
                blank=True,
                help_text="Channel name for weekly reports (optional, defaults to default_channel_name)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="slackintegration",
            name="weekly_report_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Channel ID for weekly reports (optional, defaults to default_channel_id)",
                max_length=255,
                null=True,
            ),
        ),
    ]
