# Generated by Django 5.2.8 on 2025-11-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0249_issue_spam_reason_issue_spam_score"),
        ("website", "0252_add_adventure_models"),
    ]

    operations = []
