# Generated by Django 5.1.8 on 2025-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0252_add_adventure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="webhook_secret",
            field=models.CharField(
                blank=True, help_text="Secret key for webhook authentication", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="webhook_url",
            field=models.URLField(
                blank=True, help_text="Webhook URL to trigger contributor stats recalculation", null=True
            ),
        ),
    ]
