# Generated by Django 5.1.8 on 2025-11-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0253_repo_allowed_autopay_labels_repo_autopay_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="signature",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="paymentreceipt",
            name="tx_id",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="user_profile",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="website.userprofile"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "completed", "failed", "cancelled"])),
                name="paymentrecord_valid_status",
            ),
        ),
    ]
