# Generated by Django 5.1.8 on 2025-11-23 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0253_add_tag_metadata_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Hex color code for tag display (e.g., '#e74c3c')",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex color code (e.g., '#e74c3c')",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
