# Generated by Django 5.1.8 on 2025-11-23 18:29

from django.db import migrations, models

import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0253_add_anonymous_hunt_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hunt",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="hunt",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="hunt",
            name="anonymous_payer_bch_address",
            field=models.CharField(
                blank=True,
                help_text="BCH address of anonymous payer as proof of payment availability for bug bounties",
                max_length=100,
                null=True,
                validators=[website.models.validate_bch_address],
            ),
        ),
    ]
