# Generated by Django 5.1.8 on 2025-11-24 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0253_add_verifier_permission"),
        ("website", "0253_alter_organization_logo_alter_organization_url_and_more"),
    ]

    operations = []
