# Generated by Django 5.1.8 on 2025-12-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0253_add_verifier_permission"),
        ("website", "0253_alter_organization_logo_alter_organization_url_and_more"),
    ]

    operations = []
