# Generated by Django 5.1.8 on 2025-11-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0255_add_reviewer_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="github_comment_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="issue",
            name="github_state",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
