# Generated by Django 5.1.8 on 2025-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0256_add_github_fields_to_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="github_data_fetch_failed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if fetching GitHub data failed",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="github_state",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open"), ("closed", "Closed")],
                help_text="Current state of the GitHub issue",
                max_length=10,
                null=True,
            ),
        ),
    ]
