# Generated by Django 5.1.8 on 2025-11-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0256_inviteorganization"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slack_user_count",
            field=models.IntegerField(default=0),
        ),
    ]
