# Generated by Django 5.1.8 on 2025-11-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0257_project_slack_user_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                ("channel_id", models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("topic", models.TextField(blank=True, default="")),
                ("purpose", models.TextField(blank=True, default="")),
                ("num_members", models.IntegerField(default=0)),
                ("is_private", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_general", models.BooleanField(default=False)),
                ("creator", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("slack_url", models.URLField(blank=True, default="", max_length=255)),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-num_members", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="slackchannel_name_idx"),
                    models.Index(fields=["num_members"], name="slackchannel_members_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="slack_channel_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the SlackChannel record for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="website.slackchannel",
            ),
        ),
    ]
