# Generated by Django 5.1.8 on 2025-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0257_project_slack_user_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="ip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="ip",
            index=models.Index(fields=["path", "updated_at"], name="ip_path_updated_idx"),
        ),
    ]
