# Generated by Django 5.1.8 on 2025-12-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0258_add_slackchannel_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=255)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("issues", "Issues"),
                            ("domains", "Domains"),
                            ("users", "Users"),
                            ("labels", "Labels"),
                            ("organizations", "Organizations"),
                            ("projects", "Projects"),
                            ("repos", "Repositories"),
                            ("tags", "Tags"),
                            ("languages", "Languages"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                (
                    "result_count",
                    models.PositiveIntegerField(blank=True, help_text="Number of results returned", null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search Histories",
                "ordering": ["-timestamp"],
                "indexes": [models.Index(fields=["user", "-timestamp"], name="search_hist_user_time_idx")],
            },
        ),
    ]
