# Generated by Django 5.1.8 on 2025-11-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0258_add_slackchannel_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("investigating", "Investigating"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("affected_systems", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
