# Generated by Django 5.1.8 on 2025-11-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0258_add_slackchannel_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slack_channel_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the SlackChannel record for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="website.slackchannel",
            ),
        ),
    ]
