# Generated by Django 5.1.8 on 2025-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0258_add_slackchannel_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="bounty_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
