# Generated by Django 5.1.8 on 2025-12-03 09:01

from django.db import migrations, models

import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0258_add_slackchannel_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=website.models.issue_screenshot_upload_path,
                validators=[website.models.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="issuescreenshot",
            name="image",
            field=models.ImageField(
                upload_to=website.models.issue_screenshot_upload_path, validators=[website.models.validate_image]
            ),
        ),
    ]
