# Generated by Django 5.1.8 on 2025-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0258_add_slackchannel_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="notes",
            field=models.TextField(
                blank=True, default="", help_text="Notes about detected emails and other monitoring details"
            ),
        ),
    ]
