# Generated by Django 5.1.8 on 2025-11-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0258_add_recommendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="recommendationskill",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
