# Generated by Django 5.1.8 on 2025-11-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0259_alter_recommendation_id_alter_recommendationskill_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("colleague", "Colleague"),
                    ("mentor", "Mentor"),
                    ("bug_hunter", "Bug Hunter"),
                    ("team_member", "Team Member"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Relationship between recommender and recipient",
                max_length=20,
                null=True,
            ),
        ),
    ]
