# Generated by Django 5.1.8 on 2025-12-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0259_add_search_history"),
        ("website", "0259_githubissue_bounty_expiry_date"),
    ]

    operations = []
