# Generated by Django 5.2.9 on 2025-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0259_add_search_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackbotactivity",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
