# Generated by Django 5.1.8 on 2025-12-06 18:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="check_in_count",
            field=models.IntegerField(default=0, help_text="Total check-ins recorded for leaderboard calculation"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_score_update",
            field=models.DateTimeField(
                blank=True, help_text="When the leaderboard score was last recalculated", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cached total leaderboard score (0-100)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="quality_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cached quality component score (0-100)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
