# Generated by Django 5.2.9 on 2025-12-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment_id", models.BigIntegerField(unique=True)),
                ("body", models.TextField()),
                ("comment_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("url", models.URLField()),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_comments",
                        to="website.contributor",
                    ),
                ),
                (
                    "github_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="website.githubissue"
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_comments",
                        to="website.repo",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_comments",
                        to="website.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
