# Generated by Django 5.1.8 on 2025-12-04 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0260_securityincident"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityIncidentHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="securityincident",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(fields=["severity"], name="incident_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(fields=["status"], name="incident_status_idx"),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(fields=["-created_at"], name="incident_created_idx"),
        ),
        migrations.AddField(
            model_name="securityincidenthistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="securityincidenthistory",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="history", to="website.securityincident"
            ),
        ),
    ]
