# Generated by Django 5.2.9 on 2025-12-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
        ("website", "0260_merge_20251205_1407"),
    ]

    operations = []
