# Generated by Django 5.2.9 on 2025-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_linking_reward_given",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has received bacon tokens for linking GitHub profile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_linkback_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether GitHub profile has been verified to link back to BLT",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_linkback_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the GitHub linkback was verified",
            ),
        ),
    ]
