# Generated by Django 5.2.9 on 2025-12-15 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="scope",
            field=models.CharField(choices=[("user", "User"), ("team", "Team")], default="user", max_length=10),
        ),
        migrations.CreateModel(
            name="TeamBadge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_badges_to_team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.badge")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.organization")),
            ],
        ),
    ]
