# Generated by Django 5.2.9 on 2025-12-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0249_issue_spam_reason_issue_spam_score"),
        ("website", "0260_add_username_to_slackbotactivity"),
    ]

    operations = []
