# Generated by Django 5.2.9 on 2025-12-11 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bounty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_full_name", models.CharField(max_length=200)),
                ("issue_number", models.PositiveIntegerField()),
                ("issue_url", models.URLField()),
                ("sponsor_github", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("origin_comment_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "sponsor_user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["repo_full_name", "issue_number"], name="website_bou_repo_fu_07af14_idx"),
                    models.Index(fields=["sponsor_github"], name="website_bou_sponsor_15074f_idx"),
                ],
            },
        ),
    ]
