# Generated by Django 5.2.9 on 2025-12-09 09:17
# Combined migration: Creates DailyChallenge and UserDailyChallenge models, adds next_challenge_at field

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0260_add_username_to_slackbotactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("early_checkin", "Early Check-in"),
                            ("positive_mood", "Positive Mood"),
                            ("complete_all_fields", "Complete All Fields"),
                            ("streak_milestone", "Streak Milestone"),
                            ("no_blockers", "No Blockers"),
                        ],
                        help_text="Type of daily challenge",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Display title for the challenge", max_length=255)),
                ("description", models.TextField(help_text="Description of what the challenge requires")),
                (
                    "points_reward",
                    models.IntegerField(
                        default=10,
                        help_text="Points awarded for completing this challenge",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this challenge type is currently active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Challenge",
                "verbose_name_plural": "Daily Challenges",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="UserDailyChallenge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "challenge_date",
                    models.DateField(db_index=True, help_text="Date for which this challenge is assigned"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("completed", "Completed"), ("expired", "Expired")],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "points_awarded",
                    models.IntegerField(
                        default=0, help_text="Points actually awarded (may differ from challenge.points_reward)"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the challenge was completed", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "next_challenge_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the next challenge will be available (24 hours from last check-in submission)",
                        null=True,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="website.dailychallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-challenge_date", "status"],
                "indexes": [
                    models.Index(fields=["user", "challenge_date"], name="website_use_user_id_0b6b81_idx"),
                    models.Index(fields=["status", "challenge_date"], name="website_use_status_cc8b53_idx"),
                ],
                "unique_together": {("user", "challenge_date")},
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="User's timezone (e.g., 'Asia/Kolkata', 'America/New_York'). Defaults to UTC.",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystatusreport",
            unique_together={("user", "date")},
        ),
    ]
