# Generated by Django 5.2.9 on 2025-12-09 09:17
# Combined migration: Creates DailyChallenge and UserDailyChallenge models, adds timezone field,
# handles duplicate cleanup, and creates initial challenge records

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_duplicate_daily_status_reports(apps, schema_editor):
    """
    Remove duplicate DailyStatusReport entries before applying unique_together constraint.
    For each (user, date) group, keep the record with the earliest created timestamp
    and delete the rest.
    """
    DailyStatusReport = apps.get_model("website", "DailyStatusReport")

    # Find all duplicate groups (user, date) with count > 1
    from django.db.models import Count

    duplicates = DailyStatusReport.objects.values("user", "date").annotate(count=Count("id")).filter(count__gt=1)

    deleted_count = 0
    for group in duplicates:
        user_id = group["user"]
        date = group["date"]

        # Get all records for this (user, date) group, ordered by created
        records = DailyStatusReport.objects.filter(user_id=user_id, date=date).order_by("created")

        # Keep the first one (earliest created), delete the rest
        keep_record = records.first()
        if keep_record:
            records_to_delete = records.exclude(id=keep_record.id)
            count = records_to_delete.count()
            records_to_delete.delete()
            deleted_count += count

    if deleted_count > 0:
        print(f"Removed {deleted_count} duplicate DailyStatusReport entries")


def reverse_remove_duplicates(apps, schema_editor):
    """Reverse migration - nothing to do as we can't restore deleted duplicates"""
    pass


def create_initial_daily_challenges(apps, schema_editor):
    """
    Create initial DailyChallenge records for all challenge types.
    This ensures the feature works out of the box after migration.
    """
    DailyChallenge = apps.get_model("website", "DailyChallenge")

    challenges_data = [
        {
            "challenge_type": "early_checkin",
            "title": "Early Bird",
            "description": "Submit your check-in before 10 AM in your local timezone to earn bonus points!",
            "points_reward": 15,
            "is_active": True,
        },
        {
            "challenge_type": "positive_mood",
            "title": "Positive Vibes",
            "description": "Start your day with a positive mood! Select Happy 😊 or Smile 😄 when submitting your check-in.",
            "points_reward": 10,
            "is_active": True,
        },
        {
            "challenge_type": "complete_all_fields",
            "title": "Complete Check-in",
            "description": "Fill out all fields in your daily check-in form completely to earn points.",
            "points_reward": 10,
            "is_active": True,
        },
        {
            "challenge_type": "streak_milestone",
            "title": "Streak Master",
            "description": "Reach a streak milestone (7, 15, 30, 100, 180, or 365 days) to earn bonus points!",
            "points_reward": 50,
            "is_active": True,
        },
        {
            "challenge_type": "no_blockers",
            "title": "Smooth Sailing",
            "description": "Have a blocker-free day! Select 'No blockers' when submitting your check-in.",
            "points_reward": 10,
            "is_active": True,
        },
        {
            "challenge_type": "detailed_reporter",
            "title": "Detailed Reporter",
            "description": "Write at least 200 words in your 'Previous Work' field to earn bonus points for detailed reporting!",
            "points_reward": 15,
            "is_active": True,
        },
        {
            "challenge_type": "goal_achiever",
            "title": "Goal Achiever",
            "description": "Accomplish your goals from yesterday! Select 'Yes' for goal accomplished to earn points.",
            "points_reward": 15,
            "is_active": True,
        },
        {
            "challenge_type": "detailed_planner",
            "title": "Detailed Planner",
            "description": "Plan ahead! Write at least 200 words in your 'Next Plan' field to earn bonus points for detailed planning!",
            "points_reward": 15,
            "is_active": True,
        },
    ]

    for challenge_data in challenges_data:
        DailyChallenge.objects.get_or_create(
            challenge_type=challenge_data["challenge_type"],
            defaults={
                "title": challenge_data["title"],
                "description": challenge_data["description"],
                "points_reward": challenge_data["points_reward"],
                "is_active": challenge_data["is_active"],
            },
        )


def reverse_create_challenges(apps, schema_editor):
    """Reverse migration - remove only the seeded DailyChallenge records"""
    DailyChallenge = apps.get_model("website", "DailyChallenge")
    # Only delete the challenge types that were seeded by this migration
    # This prevents wiping challenges created/edited post-deploy
    DailyChallenge.objects.filter(
        challenge_type__in=[
            "early_checkin",
            "positive_mood",
            "complete_all_fields",
            "streak_milestone",
            "no_blockers",
            "detailed_reporter",
            "goal_achiever",
            "detailed_planner",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0261_add_connected_action_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("early_checkin", "Early Check-in"),
                            ("positive_mood", "Positive Mood"),
                            ("complete_all_fields", "Complete All Fields"),
                            ("streak_milestone", "Streak Milestone"),
                            ("no_blockers", "No Blockers"),
                            ("detailed_reporter", "Detailed Reporter"),
                            ("goal_achiever", "Goal Achiever"),
                            ("detailed_planner", "Detailed Planner"),
                        ],
                        help_text="Type of daily challenge",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Display title for the challenge", max_length=255)),
                ("description", models.TextField(help_text="Description of what the challenge requires")),
                (
                    "points_reward",
                    models.IntegerField(
                        default=10,
                        help_text="Points awarded for completing this challenge",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this challenge type is currently active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Challenge",
                "verbose_name_plural": "Daily Challenges",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="UserDailyChallenge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "challenge_date",
                    models.DateField(db_index=True, help_text="Date for which this challenge is assigned"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("completed", "Completed"), ("expired", "Expired")],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "points_awarded",
                    models.IntegerField(
                        default=0, help_text="Points actually awarded (may differ from challenge.points_reward)"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the challenge was completed", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "next_challenge_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the next challenge will be available (24 hours from last check-in submission)",
                        null=True,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="website.dailychallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-challenge_date", "status"],
                "indexes": [
                    models.Index(fields=["status", "challenge_date"], name="website_use_status_cc8b53_idx"),
                ],
                "unique_together": {("user", "challenge_date")},
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="User's timezone (e.g., 'Asia/Kolkata', 'America/New_York'). Defaults to UTC.",
                max_length=50,
            ),
        ),
        migrations.RunPython(remove_duplicate_daily_status_reports, reverse_remove_duplicates),
        migrations.AlterUniqueTogether(
            name="dailystatusreport",
            unique_together={("user", "date")},
        ),
        migrations.RunPython(create_initial_daily_challenges, reverse_create_challenges),
    ]
