# Generated by Django 5.2.9 on 2025-12-06 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0261_add_recommendations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("colleague", "Colleague"),
                    ("mentor", "Mentor"),
                    ("bug_hunter", "Bug Hunter"),
                    ("team_member", "Team Member"),
                    ("other", "Other"),
                ],
                help_text="Relationship between recommender and recipient",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_user", models.F("to_user")), _negated=True),
                name="prevent_self_recommendation",
            ),
        ),
    ]
