# Generated by Django 5.2.9 on 2025-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0261_dailychallenge_userdailychallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychallenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("early_checkin", "Early Check-in"),
                    ("positive_mood", "Positive Mood"),
                    ("complete_all_fields", "Complete All Fields"),
                    ("streak_milestone", "Streak Milestone"),
                    ("no_blockers", "No Blockers"),
                    ("detailed_reporter", "Detailed Reporter"),
                    ("goal_achiever", "Goal Achiever"),
                    ("detailed_planner", "Detailed Planner"),
                ],
                help_text="Type of daily challenge",
                max_length=50,
                unique=True,
            ),
        ),
    ]
