# Generated by Django 5.1.8 on 2025-12-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0261_slackgithublink_bounty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bounties",
                to="website.issue",
            ),
        ),
    ]
