# Generated by Django 5.2.9 on 2025-12-24 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0261_merge_20251209_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="spam_score",
            field=models.IntegerField(
                blank=True,
                help_text="AI-generated spam score (0-10, ≥6 triggers moderation)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
