# Generated by Django 5.2.9 on 2025-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0261_badge_scope_teambadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="scope",
            field=models.CharField(
                choices=[("user", "User"), ("team", "Team"), ("topuser_team", "topuser_team")],
                default="user",
                max_length=20,
            ),
        ),
    ]
