# Generated by Django 5.1.8 on 2025-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0261_revert_relationship_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("colleague", "Colleague"),
                    ("mentor", "Mentor"),
                    ("bug_hunter", "Bug Hunter"),
                    ("team_member", "Team Member"),
                    ("other", "Other"),
                ],
                help_text="Relationship between recommender and recipient",
                max_length=20,
            ),
        ),
    ]
