# Generated by Django 5.2.9 on 2025-12-12 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0261_add_connected_action_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="socialaccountreward",
            new_name="website_soc_user_id_fb0840_idx",
            old_name="website_soc_user_id_provid_idx",
        ),
        migrations.AddIndex(
            model_name="githubissue",
            index=models.Index(fields=["type", "is_merged", "merged_at"], name="githubissue_pr_merged_idx"),
        ),
        migrations.AddIndex(
            model_name="githubissue",
            index=models.Index(fields=["merged_at"], name="githubissue_merged_date_idx"),
        ),
    ]
