# Generated by Django 5.2.9 on 2025-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0261_add_github_linking_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("commit", "Commit"),
                    ("issue_opened", "Issue Opened"),
                    ("issue_closed", "Issue Closed"),
                    ("issue_assigned", "Issue Assigned"),
                    ("pull_request", "Pull Request"),
                    ("comment", "Comment"),
                    ("github_link", "GitHub Profile Link"),
                ],
                default="commit",
                max_length=20,
            ),
        ),
    ]
