# Generated by Django 5.1.8 on 2025-11-27 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0262_revert_relationship_required"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommendation",
            unique_together=set(),
        ),
    ]
