# Generated by Django 5.2.9 on 2025-12-14 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0262_securityincident_securityincidenthistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="githubissue",
            index=models.Index(fields=["type", "is_merged", "merged_at"], name="githubissue_pr_merged_idx"),
        ),
        migrations.AddIndex(
            model_name="githubissue",
            index=models.Index(fields=["merged_at"], name="githubissue_merged_date_idx"),
        ),
    ]
