# Generated by Django 5.2.9 on 2025-12-13 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0262_securityincident_securityincidenthistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="socialaccountreward",
            new_name="website_soc_user_id_fb0840_idx",
            old_name="website_soc_user_id_provid_idx",
        ),
        migrations.AddIndex(
            model_name="securityincidenthistory",
            index=models.Index(fields=["incident", "-changed_at"], name="history_incident_changedat_idx"),
        ),
    ]
