# Generated by Django 5.1.8 on 2025-11-27 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_remove_unique_constraint_for_testing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="is_highlighted",
            field=models.BooleanField(
                default=False, help_text="Whether this recommendation is highlighted/pinned on the profile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recommendation_blurb",
            field=models.TextField(
                blank=True,
                help_text="Short summary/about section for recommendations (max 500 characters). NEW FIELD - additive only.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RecommendationRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from requester", max_length=500, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Status of the recommendation request",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User requesting the recommendation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User being asked to write the recommendation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Request",
                "verbose_name_plural": "Recommendation Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="recommendation",
            name="request",
            field=models.ForeignKey(
                blank=True,
                help_text="The recommendation request that led to this recommendation (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendation",
                to="website.recommendationrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationrequest",
            index=models.Index(fields=["to_user", "status"], name="rec_req_to_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendationrequest",
            index=models.Index(fields=["from_user"], name="rec_req_from_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationrequest",
            unique_together={("from_user", "to_user")},
        ),
    ]
