# Generated by Django 5.1.8 on 2026-01-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubWebhookConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Optional project-specific webhook secret. Leave blank to use global secret.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stats_recalc_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic contributor stats recalculation on webhook events"
                    ),
                ),
                (
                    "last_webhook_received",
                    models.DateTimeField(blank=True, help_text="Timestamp of last webhook received", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project associated with this webhook configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_webhook_config",
                        to="website.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Webhook Configuration",
                "verbose_name_plural": "GitHub Webhook Configurations",
            },
        ),
    ]
