# Generated by Django 5.2.9 on 2026-01-09 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="freshness",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="0..100 freshness score representing recent project activity",
                max_digits=5,
            ),
        ),
    ]
