# Generated by Django 5.2.9 on 2025-12-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0261_issuepledge"),
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = []
