# Generated by Django 5.2.9 on 2026-01-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        # Add indexes to improve search performance
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["hunt"], name="issue_hunt_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["is_hidden"], name="issue_hidden_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["hunt", "is_hidden"], name="issue_hunt_hidden_idx"),
        ),
        # Add index for commonly filtered Organization fields
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="org_name_idx"),
        ),
        # Add index for Project searches
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name"], name="project_name_idx"),
        ),
        # Add index for Repo searches
        migrations.AddIndex(
            model_name="repo",
            index=models.Index(fields=["name"], name="repo_name_idx"),
        ),
        migrations.AddIndex(
            model_name="repo",
            index=models.Index(fields=["primary_language"], name="repo_language_idx"),
        ),
    ]
