# Generated by Django 5.2.9 on 2026-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trademark",
            name="filing_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="keyword",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="registration_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="serial_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="trademark",
            name="status_code",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
