# Generated by Django 5.2.9 on 2025-12-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0262_alter_issue_spam_score"),
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = []
