# Generated by Django 5.1.8 on 2025-12-14 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_bounty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bounty",
            name="bounty_amount_gt_zero",
        ),
        migrations.AddConstraint(
            model_name="bounty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("sponsor", "github_issue_url"),
                name="uniq_pending_bounty_per_sponsor_issue",
            ),
        ),
    ]
