# Generated by Django 5.1.8 on 2025-12-18 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("bug_report", "Bug Report"),
                            ("bug_comment", "Bug Comment"),
                            ("bug_view", "Bug View"),
                            ("dashboard_visit", "Dashboard Visit"),
                            ("profile_update", "Profile Update"),
                            ("company_subscribe", "Company Subscribe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_activities",
                        to="website.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "indexes": [
                    models.Index(fields=["user", "timestamp"], name="user_activity_user_time_idx"),
                    models.Index(fields=["organization", "activity_type"], name="user_activity_org_type_idx"),
                    models.Index(fields=["activity_type", "timestamp"], name="user_activity_type_time_idx"),
                    models.Index(fields=["organization", "timestamp"], name="user_activity_org_time_idx"),
                ],
            },
        ),
    ]
