# Generated by Django 5.2.9 on 2026-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="freshness",
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="project",
            name="freshness_history",
            field=models.JSONField(
                blank=True, default=list, help_text="Last 12 freshness scores with timestamps for sparkline chart"
            ),
        ),
    ]
