# Generated by Django 5.2.9 on 2026-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="bounty_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
