# Generated by Django 5.1.8 on 2025-12-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0247_job"),
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = []
