# Generated by Django 4.2.24 on 2026-01-21 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlaggedContent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("promotional", "Promotional/Advertising Spam"),
                            ("malicious", "Malicious Links/Phishing"),
                            ("low_quality", "Low Quality/Irrelevant"),
                            ("duplicate", "Duplicate/Template Spam"),
                            ("social_engineering", "Social Engineering"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "spam_score",
                    models.FloatField(
                        help_text="AI confidence score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "spam_categories",
                    models.JSONField(blank=True, default=list, help_text="List of detected spam categories from AI"),
                ),
                (
                    "detection_details",
                    models.TextField(blank=True, help_text="Detailed explanation from AI spam detection"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved - Not Spam"),
                            ("rejected", "Rejected - Is Spam"),
                            ("auto_rejected", "Auto-Rejected - High Confidence Spam"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, help_text="Notes from moderator about the resolution"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator assigned to review this content",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_flagged_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reported this (null if auto-detected by AI)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_content_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flagged Content",
                "verbose_name_plural": "Flagged Content",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("flagged", "Content Flagged"),
                            ("assigned", "Assigned to Reviewer"),
                            ("approved", "Approved - Not Spam"),
                            ("rejected", "Rejected - Is Spam"),
                            ("note_added", "Note Added"),
                            ("status_changed", "Status Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="website.flaggedcontent",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action (null if automatic)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Action",
                "verbose_name_plural": "Moderation Actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["flagged_content", "-created_at"], name="modaction_content_created_idx"),
                    models.Index(fields=["action"], name="modaction_action_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(fields=["status", "-created_at"], name="flagged_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(fields=["assigned_reviewer"], name="flagged_reviewer_idx"),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(fields=["content_type", "object_id"], name="flagged_content_type_idx"),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(fields=["-spam_score"], name="flagged_spam_score_idx"),
        ),
    ]
