# Generated by Django 5.2.9 on 2025-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="freshness",
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
