# Generated by Django 5.1.8 on 2025-12-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="artifact_sha256",
            field=models.CharField(
                blank=True, help_text="SHA-256 of the encrypted disclosure artifact sent to the org.", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, help_text="When the encrypted artifact delivery completed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="delivery_method",
            field=models.CharField(blank=True, help_text="Delivery channel, e.g. email:smtp.", max_length=50),
        ),
        migrations.AddField(
            model_name="issue",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                help_text="Zero-trust pipeline status: pending_build, delivered, failed, etc.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="encryption_method",
            field=models.CharField(
                blank=True, help_text="Encryption method used (e.g. age, openpgp, sym_7z).", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_zero_trust",
            field=models.BooleanField(
                default=False,
                help_text="If true, this issue was submitted via the zero-trust pipeline; no PoC/plaintext stored.",
            ),
        ),
        migrations.CreateModel(
            name="OrgEncryptionConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Disclosure contact for this organization (receives encrypted artifacts).",
                        max_length=254,
                    ),
                ),
                (
                    "preferred_method",
                    models.CharField(
                        choices=[
                            ("age", "age (public key)"),
                            ("openpgp", "OpenPGP (GnuPG)"),
                            ("sym_7z", "Symmetric 7z (AES-256, OOB password)"),
                        ],
                        default="age",
                        max_length=20,
                    ),
                ),
                (
                    "age_recipient",
                    models.CharField(
                        blank=True, help_text="age recipient string (e.g. age1...) if using age.", max_length=255
                    ),
                ),
                (
                    "pgp_fingerprint",
                    models.CharField(blank=True, help_text="OpenPGP key fingerprint if using GnuPG.", max_length=64),
                ),
                ("pgp_key_text", models.TextField(blank=True, help_text="Optional ASCII-armored public key text.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_config",
                        to="website.organization",
                    ),
                ),
            ],
        ),
    ]
