# Generated by Django 5.2.9 on 2026-01-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="scope",
            field=models.CharField(
                choices=[("user", "User"), ("team", "Team"), ("topuser_team", "Topuser Team")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="awarded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="awarded_badges_to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TeamBadge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_badges_to_team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.badge")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.organization")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("team", "badge"), name="unique_team_badge_per_team"),
                    models.UniqueConstraint(fields=("team", "user", "badge"), name="unique_user_badge_per_team"),
                ],
            },
        ),
    ]
