# Generated by Django 5.1.8 on 2025-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0264_add_recommendation_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Status of the recommendation request",
                max_length=20,
            ),
        ),
    ]
