# Generated by Django 5.2.9 on 2026-01-11 07:36

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0264_project_freshness"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(blank=True, related_name="projects", to="website.contributor"),
        ),
        migrations.AlterField(
            model_name="project",
            name="freshness",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="0..100 freshness score representing recent project activity",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
