# Generated by Django 5.2.11 on 2026-02-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0264_add_timelog_pause_resume_fields'),
        ('website', '0264_remove_forum_models'),
    ]

    operations = [
    ]
