# Generated by Django 5.2.9 on 2026-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0264_remove_forum_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
