# Generated by Django 5.1.8 on 2025-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0264_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="user_agent",
            field=models.TextField(blank=True, default="", max_length=512),
        ),
    ]
