# Generated by Django 5.2.11 on 2026-02-14 17:51

from django.db import migrations, models

import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0264_remove_forum_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="eth_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, validators=[website.models.validate_eth_address]
            ),
        ),
    ]
