# Generated by Django 5.2.11 on 2026-02-09 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0263_githubissue_githubissue_pr_merged_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BannedApp",
        ),
    ]
