# Generated by Django 5.2.9 on 2026-01-16 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0264_badge_scope_alter_userbadge_awarded_by_teambadge"),
    ]

    operations = []
