# Generated by Django 5.2.11 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0264_remove_forum_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="bounty_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

