# Generated by Django 5.2.11 on 2026-02-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0265_delete_bannedapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
