# Generated by Django 5.1.8 on 2026-02-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0247_job"),
        ("website", "0265_delete_bannedapp"),
    ]

    operations = []
