# Generated by Django 5.1.8 on 2025-12-18 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0265_alter_useractivity_user_agent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["organization", "timestamp"], name="user_activity_org_time_idx"),
        ),
    ]
