# Generated by Django 5.1.8 on 2025-11-25 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0265_delete_bannedapp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Fix CVE score max_digits to support scores up to 10.0
        migrations.AlterField(
            model_name="issue",
            name="cve_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        # Increase CVE ID max_length to support longer CVE IDs
        migrations.AlterField(
            model_name="issue",
            name="cve_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Add indexes for CVE fields (after field alterations)
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["cve_id"], name="issue_cve_id_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["cve_score"], name="issue_cve_score_idx"),
        ),
    ]
