# Generated by Django 5.1.8 on 2025-11-27 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0265_alter_recommendationrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommendation",
            unique_together={("from_user", "to_user")},
        ),
    ]
