# Generated by Django 5.2.9 on 2026-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0265_delete_bannedapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertasksubmission",
            name="proof_url",
            field=models.URLField(blank=True, help_text="Link to pull request, issue, or other evidence"),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
