# Generated by Django 5.2.11 on 2026-03-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0265_delete_bannedapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="vector_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Stores the OpenAI semantic vector embedding array for duplicate detection",
                null=True,
            ),
        ),
    ]
