# Generated by Django 5.2.11 on 2026-02-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0266_add_cve_indexes"),
        ("website", "0266_alter_usertasksubmission_proof_url_delete_post"),
    ]

    operations = []
