# Generated by Django 5.2.11 on 2026-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0266_alter_usertasksubmission_proof_url_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
