# Generated by Django 5.2.9 on 2026-01-11 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0266_project_freshness_checkconstraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="freshness_0_100_range",
        ),
    ]
