# Generated by Django 5.2.x on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0266_alter_usertasksubmission_proof_url_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="spam_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="spam_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
