# Generated by Django 5.1.8 on 2026-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0266_merge_0247_job_0265_delete_bannedapp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumpost",
            name="category",
        ),
        migrations.RemoveField(
            model_name="forumcomment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="forumcomment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="forumcomment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="forumpost",
            name="user",
        ),
        migrations.RemoveField(
            model_name="forumvote",
            name="post",
        ),
        migrations.RemoveField(
            model_name="forumvote",
            name="user",
        ),
        migrations.AddField(
            model_name="organization",
            name="linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_clicks",
            field=models.JSONField(
                default=dict, help_text="Track social media profile visits (Twitter, GitHub, LinkedIn, Facebook)"
            ),
        ),
        migrations.DeleteModel(
            name="ForumCategory",
        ),
        migrations.DeleteModel(
            name="ForumComment",
        ),
        migrations.DeleteModel(
            name="ForumPost",
        ),
        migrations.DeleteModel(
            name="ForumVote",
        ),
    ]
