# Generated by Django 5.2.11 on 2026-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0267_merge_20260218_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
