# Generated by Django 5.2.11 on 2026-02-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0267_merge_20260218_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="freshness",
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="repo",
            name="participation_stats",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
