# Generated by Django 5.2.11 on 2026-02-18 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0266_add_cve_indexes"),
        ("website", "0267_githubissue_bounty_expiry_date_and_more"),
    ]

    operations = []
