# Generated by Django 5.2.9 on 2026-02-20 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0268_project_freshness_repo_participation_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="freshness",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("bug", "Bug"),
                    ("organization", "Organization"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
