# Generated by Django 5.2.9 on 2026-02-23 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0269_alter_project_freshness_alter_room_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment_id", models.BigIntegerField(unique=True)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("url", models.URLField()),
                (
                    "commenter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_comments_as_user",
                        to="website.userprofile",
                    ),
                ),
                (
                    "commenter_contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_comments_as_contributor",
                        to="website.contributor",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_comments",
                        to="website.githubissue",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="gh_comment_created_idx"),
                    models.Index(fields=["commenter_contributor"], name="gh_comment_contributor_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("commenter__isnull", False), ("commenter_contributor__isnull", False), _connector="OR"
                        ),
                        name="at_least_one_commenter",
                    )
                ],
            },
        ),
    ]
