# Generated by Django 5.2.11 on 2026-02-22 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0269_alter_project_freshness_alter_room_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyStatusReport",
        ),
    ]
