# Generated by Django 5.2.11 on 2026-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0267_merge_20260219_0058"),
        ("website", "0269_alter_project_freshness_alter_room_type"),
    ]

    operations = []
