# Generated by Django 5.2.11 on 2026-02-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0269_add_org_security_monitoring"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbehavioranomaly",
            options={"ordering": ["-created_at"], "verbose_name_plural": "User behavior anomalies"},
        ),
    ]
