# Generated by Django 5.1.8 on 2026-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0269_alter_project_freshness_alter_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_clicks",
            field=models.JSONField(
                default=dict,
                help_text="Track social media profile visits (Twitter, GitHub, LinkedIn, Facebook)",
            ),
        ),
    ]
