# Generated by Django 5.2.11 on 2026-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0269_alter_project_freshness_alter_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
