# Generated by Django 5.2.11 on 2026-02-26 16:28

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0270_githubcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="eth_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, validators=[website.models.validate_eth_address]
            ),
        ),
    ]
