# Generated by Django 5.1.8 on 2026-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0270_githubcomment"),
        ("website", "0270_add_issue_verification_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_clicks",
            field=models.JSONField(
                default=dict, help_text="Track social media profile visits (Twitter, GitHub, LinkedIn, Facebook)"
            ),
        ),
    ]
