# Generated by Django 5.2.11 on 2026-02-23 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0270_githubcomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatBotLog",
        ),
        migrations.DeleteModel(
            name="SlackBotActivity",
        ),
        migrations.RemoveField(
            model_name="slackintegration",
            name="integration",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack_channel",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack_user_count",
        ),
        migrations.DeleteModel(
            name="SlackChannel",
        ),
        migrations.DeleteModel(
            name="SlackIntegration",
        ),
    ]
