# Generated by Django 5.2.11 on 2026-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0270_githubcomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SlackBotActivity",
        ),
        migrations.RemoveField(
            model_name="slackintegration",
            name="integration",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="slack_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack_channel",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slack_user_count",
        ),
        migrations.AlterField(
            model_name="integration",
            name="service_name",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name="SlackChannel",
        ),
        migrations.DeleteModel(
            name="SlackIntegration",
        ),
    ]
