# Generated by Django 5.2.11 on 2026-02-21 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0270_githubcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["status"], name="issue_status_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["label"], name="issue_label_idx"),
        ),
    ]
