# Generated by Django 5.2.11 on 2026-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0271_make_email_unique_safe"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
