# Generated by Django 5.2.9 on 2026-03-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0271_make_email_unique_safe"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_clicks",
            field=models.JSONField(
                default=dict, help_text="Track social media profile visits (Twitter, GitHub, LinkedIn, Facebook)"
            ),
        ),
    ]
