# Generated by Django 5.2.11 on 2026-03-04 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0271_make_email_unique_safe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_score",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="dailystatusreport",
            index=models.Index(fields=["user", "date"], name="dsr_user_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailystatusreport",
            constraint=models.UniqueConstraint(fields=("user", "date"), name="unique_dsr_user_date"),
        ),
    ]
