# Generated by Django 5.2.11 on 2026-03-04 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0272_organization_linkedin_organization_social_clicks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="points",
            index=models.Index(fields=["user", "created"], name="points_user_created_idx"),
        ),
    ]
