# Generated by Django 5.2.11 on 2026-03-05 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0272_userprofile_leaderboard_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="spam_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="spam_score",
            field=models.IntegerField(
                blank=True,
                help_text="AI-generated spam score (0-10, ≥6 triggers moderation)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
