# Generated by Django 1.9.2 on 2017-06-06 20:49


import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0026_auto_20170606_2049"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("author", models.CharField(max_length=200)),
                ("author_url", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="website.Issue",
                    ),
                ),
            ],
        ),
    ]
