# Generated by Django 5.1.4 on 2025-02-27 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("website", "0211_course_lecture_lecturestatus_rating_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("author", models.CharField(max_length=200)),
                ("author_url", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author_fk",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="website.userprofile"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "parent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="comments.comment"),
                ),
            ],
        ),
    ]
