# Generated by Django 1.11.1 on 2017-07-26 13:48


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_comment_parentid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parentId",
            new_name="parent",
        ),
    ]
