# Generated by Django 1.11.1 on 2017-07-27 13:08


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_auto_20170726_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.Comment",
            ),
        ),
    ]
