# Generated by Django 5.2.11 on 2026-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0007_remove_comment_issue_comment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(help_text="The name or username of the person posting the comment.", max_length=200),
        ),
    ]
