# Generated by Django 5.2.11 on 2026-02-21 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sizzle", "0001_initial"),
    ]

    operations = []
