# Generated by Django 5.2.11 on 2026-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sizzle", "0002_auto_20260221_1743"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystatusreport",
            name="duration",
            field=models.CharField(default="0h 0m", max_length=50),
        ),
        migrations.AddField(
            model_name="dailystatusreport",
            name="issue_title",
            field=models.CharField(default="General Update", max_length=255),
        ),
        migrations.AddField(
            model_name="dailystatusreport",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
