# Generated by Django 5.1.3 on 2024-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0004_alter_team_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
