# Generated by Django 5.1.3 on 2024-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0006_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="fresh_points",
            field=models.IntegerField(default=0),
        ),
    ]
