# Generated by Django 5.1.3 on 2024-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0009_challenge_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="fresh_points",
            field=models.IntegerField(default=0),
        ),
    ]
