from company.views import ShowBughuntView, SlackCallbackView
from dj_rest_auth.registration.views import SocialAccountDisconnectView, SocialAccountListView
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

import comments.views
from blt import settings
from website.api.views import (
    ActivityLogViewSet,
    AuthApiViewset,
    BugHuntApiViewset,
    BugHuntApiViewsetV2,
    CompanyViewSet,
    DomainViewSet,
    FlagIssueApiView,
    InviteFriendApiViewset,
    IssueViewSet,
    LeaderboardApiViewSet,
    LikeIssueApiView,
    ProjectViewSet,
    StatsApiViewset,
    TagApiViewset,
    TimeLogViewSet,
    UrlCheckApiViewset,
    UserIssueViewSet,
    UserProfileViewSet,
)
from website.views.blog import (
    PostCreateView,
    PostDeleteView,
    PostDetailView,
    PostListView,
    PostUpdateView,
)
from website.views.company import (
    AddDomainView,
    AddHuntView,
    AddSlackIntegrationView,
    CompanyDashboardAnalyticsView,
    CompanyDashboardIntegrations,
    CompanyDashboardManageBughuntView,
    CompanyDashboardManageBugsView,
    CompanyDashboardManageDomainsView,
    CompanyDashboardManageRolesView,
    DomainView,
    EndBughuntView,
    RegisterCompanyView,
    accept_bug,
    company_view,
    delete_manager,
    delete_prize,
    edit_prize,
)
from website.views.core import (
    FacebookConnect,
    FacebookLogin,
    GithubConnect,
    GithubLogin,
    GoogleConnect,
    GoogleLogin,
    StatsDetailView,
    UploadCreate,
    add_suggestions,
    badge_list,
    chatbot_conversation,
    check_status,
    donate_view,
    facebook_callback,
    find_key,
    github_callback,
    google_callback,
    home,
    robots_txt,
    search,
    set_vote_status,
    sitemap,
    sponsor_view,
    view_suggestions,
    vote_suggestions,
)
from website.views.issue import (
    AllIssuesView,
    IssueCreate,
    IssueEdit,
    IssueView,
    SaveBiddingData,
    SpecificIssuesView,
    UpdateIssue,
    change_bid_status,
    comment_on_issue,
    create_github_issue,
    delete_comment,
    delete_issue,
    dislike_issue,
    fetch_current_bid,
    flag_issue,
    generate_bid_image,
    get_unique_issues,
    issue_count,
    like_issue,
    newhome,
    remove_user_from_issue,
    resolve,
    save_issue,
    search_issues,
    select_bid,
    submit_bug,
    submit_pr,
    unsave_issue,
    update_comment,
    vote_count,
)
from website.views.organization import (
    CompanySettings,
    CreateHunt,
    DomainDetailView,
    DomainList,
    DomainListView,
    DraftHunts,
    HuntCreate,
    InboundParseWebhookView,
    JoinCompany,
    ListHunts,
    OngoingHunts,
    PreviousHunts,
    ReportedIpListView,
    ReportIpView,
    ScoreboardView,
    TimeLogListAPIView,
    TimeLogListView,
    UpcomingHunts,
    add_domain_to_company,
    add_or_update_company,
    add_or_update_domain,
    add_role,
    add_sizzle_checkIN,
    admin_company_dashboard,
    admin_company_dashboard_detail,
    approve_activity,
    checkIN,
    checkIN_detail,
    company_dashboard,
    company_dashboard_domain_detail,
    company_dashboard_hunt_detail,
    company_dashboard_hunt_edit,
    company_hunt_results,
    delete_time_entry,
    dislike_activity,
    feed,
    get_scoreboard,
    hunt_results,
    like_activity,
    sizzle,
    sizzle_daily_log,
    sizzle_docs,
    subscribe_to_domains,
    trademark_detailview,
    trademark_search,
    update_role,
    user_sizzle_report,
    view_hunt,
    weekly_report,
)
from website.views.project import (
    ProjectBadgeView,
    ProjectDetailView,
    ProjectListView,
    blt_tomato,
    distribute_bacon,
    select_contribution,
)
from website.views.user import (
    CustomObtainAuthToken,
    EachmonthLeaderboardView,
    GlobalLeaderboardView,
    InviteCreate,
    SpecificMonthLeaderboardView,
    UserDeleteView,
    UserProfileDetailsView,
    UserProfileDetailView,
    addbalance,
    assign_badge,
    badge_user_list,
    contributors,
    contributors_view,
    create_wallet,
    deletions,
    follow_user,
    get_score,
    github_webhook,
    invite_friend,
    profile,
    profile_edit,
    referral_signup,
    stripe_connected,
    update_bch_address,
    user_dashboard,
    users_view,
    withdraw,
)

favicon_view = RedirectView.as_view(url="/static/favicon.ico", permanent=True)

router = routers.DefaultRouter()
router.register(r"issues", IssueViewSet, basename="issues")
router.register(r"userissues", UserIssueViewSet, basename="userissues")
router.register(r"profile", UserProfileViewSet, basename="profile")
router.register(r"domain", DomainViewSet, basename="domain")
router.register(r"timelogs", TimeLogViewSet, basename="timelogs")
router.register(r"activitylogs", ActivityLogViewSet, basename="activitylogs")

from allauth.socialaccount.providers.facebook import views as facebook_views
from allauth.socialaccount.providers.github import views as github_views
from allauth.socialaccount.providers.google import views as google_views
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()
schema_view = get_schema_view(
    openapi.Info(
        title="API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

handler404 = "website.views.core.handler404"
handler500 = "website.views.core.handler500"

urlpatterns = [
    path("", home, name="home"),
    path(
        "api/v1/companies/",
        CompanyViewSet.as_view({"get": "list", "post": "create"}),
        name="company",
    ),
    path("invite-friend/", invite_friend, name="invite_friend"),
    path("referral/", referral_signup, name="referral_signup"),
    path("captcha/", include("captcha.urls")),
    re_path(r"^auth/registration/", include("dj_rest_auth.registration.urls")),
    path(
        "rest-auth/password/reset/confirm/<str:uidb64>/<str:token>",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(r"^auth/", include("dj_rest_auth.urls")),
    re_path("auth/facebook", FacebookLogin.as_view(), name="facebook_login"),
    path("accounts/", include("allauth.urls")),
    path("accounts/delete/", UserDeleteView.as_view(), name="delete"),
    path("auth/github/", GithubLogin.as_view(), name="github_login"),
    path("auth/google/", GoogleLogin.as_view(), name="google_login"),
    path("accounts/github/login/callback/", github_callback, name="github_callback"),
    path("accounts/google/login/callback/", google_callback, name="google_callback"),
    path("accounts/facebook/login/callback/", facebook_callback, name="facebook_callback"),
    re_path(r"^auth/facebook/connect/$", FacebookConnect.as_view(), name="facebook_connect"),
    re_path(r"^auth/github/connect/$", GithubConnect.as_view(), name="github_connect"),
    re_path(r"^auth/google/connect/$", GoogleConnect.as_view(), name="google_connect"),
    path("auth/github/url/", github_views.oauth2_login),
    path("oauth/slack/callback/", SlackCallbackView.as_view(), name="slack_callback"),
    path("auth/google/url/", google_views.oauth2_login),
    path("auth/facebook/url/", facebook_views.oauth2_callback),
    path("socialaccounts/", SocialAccountListView.as_view(), name="social_account_list"),
    path("add_domain_to_company/", add_domain_to_company, name="add_domain_to_company"),
    path(
        "socialaccounts/<int:pk>/disconnect/",
        SocialAccountDisconnectView.as_view(),
        name="social_account_disconnect",
    ),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    re_path(r"^issues/$", newhome, name="issues"),
    re_path(
        r"^dashboard/company/$",
        company_dashboard,
        name="company_dashboard_home",
    ),
    re_path(
        r"^dashboard/user/profile/addbalance$",
        addbalance,
        name="addbalance",
    ),
    re_path(r"^dashboard/user/profile/withdraw$", withdraw, name="withdraw"),
    re_path(
        r"^dashboard/user/stripe/connected/(?P<username>[^/]+)/$",
        stripe_connected,
        name="stripe_connected",
    ),
    re_path(
        r"^dashboard/admin/company$",
        admin_company_dashboard,
        name="admin_company_dashboard",
    ),
    re_path(
        r"^dashboard/admin/company/addorupdate$",
        add_or_update_company,
        name="add_or_update_company",
    ),
    re_path(
        r"^dashboard/company/domain/addorupdate$",
        add_or_update_domain,
        name="add_or_update_domain",
    ),
    path(
        "dashboard/company/domain/<int:pk>/",
        company_dashboard_domain_detail,
        name="company_dashboard_domain_detail",
    ),
    path(
        "dashboard/company/hunt/<int:pk>/",
        company_dashboard_hunt_detail,
        name="company_dashboard_hunt_detail",
    ),
    path("dashboard/user/hunt/<int:pk>/", view_hunt, name="view_hunt"),
    path(
        "dashboard/user/hunt/<int:pk>/submittion/",
        submit_bug,
        name="submit_bug",
    ),
    path(
        "dashboard/user/hunt/<int:pk>/results/",
        hunt_results,
        name="hunt_results",
    ),
    path(
        "dashboard/company/hunt/<int:pk>/edit",
        company_dashboard_hunt_edit,
        name="company_dashboard_hunt_edit",
    ),
    path(
        "dashboard/admin/company/<int:pk>/",
        admin_company_dashboard_detail,
        name="admin_company_dashboard_detail",
    ),
    re_path(r"^dashboard/company/hunt/create$", CreateHunt.as_view(), name="create_hunt"),
    path("hunt/<int:pk>", ShowBughuntView.as_view(), name="show_bughunt"),
    re_path(r"^dashboard/company/hunt/drafts$", DraftHunts.as_view(), name="draft_hunts"),
    re_path(
        r"^dashboard/company/hunt/upcoming$",
        UpcomingHunts.as_view(),
        name="upcoming_hunts",
    ),
    re_path(
        r"^dashboard/company/hunt/previous$",
        PreviousHunts.as_view(),
        name="previous_hunts",
    ),
    path(
        "dashboard/company/hunt/previous/<int:pk>/",
        company_hunt_results,
        name="company_hunt_results",
    ),
    re_path(
        r"^dashboard/company/hunt/ongoing$",
        OngoingHunts.as_view(),
        name="ongoing_hunts",
    ),
    re_path(r"^dashboard/company/domains$", DomainList.as_view(), name="domain_list"),
    re_path(
        r"^dashboard/company/settings$",
        CompanySettings.as_view(),
        name="company-settings",
    ),
    re_path(r"^join$", JoinCompany.as_view(), name="join"),
    re_path(
        r"^dashboard/company/settings/role/update$",
        update_role,
        name="update-role",
    ),
    re_path(
        r"^dashboard/company/settings/role/add$",
        add_role,
        name="add-role",
    ),
    re_path(r"^dashboard/user/$", user_dashboard, name="user"),
    re_path(
        r"^dashboard/user/profile/(?P<slug>[^/]+)/$",
        UserProfileDetailsView.as_view(),
        name="user_profile",
    ),
    path(settings.ADMIN_URL + "/", admin.site.urls),
    re_path(r"^like_issue/(?P<issue_pk>\d+)/$", like_issue, name="like_issue"),
    re_path(
        r"^dislike_issue/(?P<issue_pk>\d+)/$",
        dislike_issue,
        name="dislike_issue",
    ),
    re_path(r"^flag_issue/(?P<issue_pk>\d+)/$", flag_issue, name="flag_issue"),
    re_path(r"^resolve/(?P<id>\w+)/$", resolve, name="resolve"),
    re_path(r"^create_github_issue/(?P<id>\w+)/$", create_github_issue, name="create_github_issue"),
    re_path(r"^vote_count/(?P<issue_pk>\d+)/$", vote_count, name="vote_count"),
    path("domain/<int:pk>/subscribe/", subscribe_to_domains, name="subscribe_to_domains"),
    re_path(r"^save_issue/(?P<issue_pk>\d+)/$", save_issue, name="save_issue"),
    path("domain/<int:pk>/subscribe/", subscribe_to_domains, name="subscribe_to_domains"),
    re_path(r"^save_issue/(?P<issue_pk>\d+)/$", save_issue, name="save_issue"),
    path("domain/<int:pk>/subscribe/", subscribe_to_domains, name="subscribe_to_domains"),
    re_path(r"^save_issue/(?P<issue_pk>\d+)/$", save_issue, name="save_issue"),
    path("profile/edit/", profile_edit, name="profile_edit"),
    re_path(
        r"^unsave_issue/(?P<issue_pk>\d+)/$",
        unsave_issue,
        name="unsave_issue",
    ),
    re_path(r"^issue/edit/$", IssueEdit, name="edit_issue"),
    re_path(r"^issue/update/$", UpdateIssue, name="update_issue"),
    path(
        "issue/<str:issue_pk>/comment/",
        comment_on_issue,
        name="comment_on_issue",
    ),
    # UPDATE COMMENT
    path(
        "issue/<str:issue_pk>/comment/update/<str:comment_pk>/",
        update_comment,
        name="update_comment",
    ),
    # delete_comment
    path("issue2/comment/delete/", delete_comment, name="delete_comment"),
    re_path(r"^issue/(?P<slug>\w+)/$", IssueView.as_view(), name="issue_view"),
    re_path(r"^follow/(?P<user>[^/]+)/", follow_user, name="follow_user"),
    re_path(r"^all_activity/$", AllIssuesView.as_view(), name="all_activity"),
    re_path(r"^label_activity/$", SpecificIssuesView.as_view(), name="all_activitys"),
    re_path(r"^leaderboard/$", GlobalLeaderboardView.as_view(), name="leaderboard_global"),
    re_path(
        r"^leaderboard/monthly/$",
        SpecificMonthLeaderboardView.as_view(),
        name="leaderboard_specific_month",
    ),
    re_path(
        r"^leaderboard/each-month/$",
        EachmonthLeaderboardView.as_view(),
        name="leaderboard_eachmonth",
    ),
    re_path(
        r"^api/v1/issue/like/(?P<id>\w+)/$",
        LikeIssueApiView.as_view(),
        name="api_like_issue",
    ),
    re_path(
        r"^api/v1/issue/flag/(?P<id>\w+)/$",
        FlagIssueApiView.as_view(),
        name="api_flag_issue",
    ),
    re_path(r"^api/v1/leaderboard/$", LeaderboardApiViewSet.as_view(), name="leaderboard"),
    re_path(
        r"^api/v1/invite_friend/",
        InviteFriendApiViewset.as_view(),
        name="api_invite_friend",
    ),
    re_path(r"^scoreboard/$", ScoreboardView.as_view(), name="scoreboard"),
    re_path(r"^issue/$", IssueCreate.as_view(), name="issue"),
    re_path(
        r"^upload/(?P<time>[^/]+)/(?P<hash>[^/]+)/",
        UploadCreate.as_view(),
        name="upload",
    ),
    re_path(r"^profile/(?P<slug>[^/]+)/$", UserProfileDetailView.as_view(), name="profile"),
    re_path(r"^domain/(?P<slug>.+)/$", DomainDetailView.as_view(), name="domain"),
    re_path(
        r"^.well-known/acme-challenge/(?P<token>[^/]+)/$",
        find_key,
        name="find_key",
    ),
    re_path(r"^accounts/profile/", profile, name="account_profile"),
    re_path(r"^delete_issue/(?P<id>\w+)/$", delete_issue, name="delete_issue"),
    re_path(
        r"^remove_user_from_issue/(?P<id>\w+)/$",
        remove_user_from_issue,
        name="remove_user_from_issue",
    ),
    re_path(r"^accounts/", include("allauth.urls")),
    re_path(
        r"^sitemap/$",
        sitemap,
        name="sitemap",
    ),
    re_path(
        r"^badges/$",
        badge_list,
        name="badges",
    ),
    re_path(
        r"^badges/(?P<badge_id>\d+)/users/$",
        badge_user_list,
        name="badge_user_list",
    ),
    re_path(r"^start/$", TemplateView.as_view(template_name="hunt.html"), name="start_hunt"),
    re_path(r"^hunt/$", login_required(HuntCreate.as_view()), name="hunt"),
    re_path(r"^hunts/$", ListHunts.as_view(), name="hunts"),
    re_path(r"^invite/$", InviteCreate.as_view(template_name="invite.html"), name="invite"),
    re_path(r"^terms/$", TemplateView.as_view(template_name="terms.html"), name="terms"),
    re_path(r"^about/$", TemplateView.as_view(template_name="about.html"), name="about"),
    re_path(r"^teams/$", TemplateView.as_view(template_name="teams.html"), name="teams"),
    re_path(
        r"^googleplayapp/$",
        TemplateView.as_view(template_name="coming_soon.html"),
        name="googleplayapp",
    ),
    re_path(r"^projects/$", ProjectListView.as_view(), name="project_list"),
    re_path(r"^apps/$", TemplateView.as_view(template_name="apps.html"), name="apps"),
    re_path(
        r"^deletions/$",
        deletions,
        name="deletions",
    ),
    re_path(r"^bacon/$", TemplateView.as_view(template_name="bacon.html"), name="bacon"),
    re_path(r"^bltv/$", TemplateView.as_view(template_name="bltv.html"), name="bltv"),
    re_path(r"^gsoc/$", TemplateView.as_view(template_name="gsoc.html"), name="gsoc"),
    re_path(
        r"^privacypolicy/$",
        TemplateView.as_view(template_name="privacy.html"),
        name="privacy",
    ),
    re_path(r"^stats/$", StatsDetailView.as_view(), name="stats"),
    re_path(r"^favicon\.ico$", favicon_view),
    re_path(
        r"^sendgrid_webhook/$",
        csrf_exempt(InboundParseWebhookView.as_view()),
        name="inbound_event_webhook_callback",
    ),
    re_path(r"status/", check_status, name="check_status"),
    re_path(r"^issue/comment/add/$", comments.views.add_comment, name="add_comment"),
    re_path(r"^issue/comment/delete/$", comments.views.delete_comment, name="delete_comment"),
    re_path(r"^comment/autocomplete/$", comments.views.autocomplete, name="autocomplete"),
    re_path(
        r"^issue/(?P<pk>\d+)/comment/edit/$",
        comments.views.edit_comment,
        name="edit_comment",
    ),
    re_path(
        r"^issue/(?P<pk>\d+)/comment/reply/$",
        comments.views.reply_comment,
        name="reply_comment",
    ),
    re_path(r"^social/$", TemplateView.as_view(template_name="social.html"), name="social"),
    re_path(r"^search/$", search, name="search"),
    re_path(r"^report/$", IssueCreate.as_view(), name="report"),
    re_path(r"^i18n/", include("django.conf.urls.i18n")),
    re_path(r"^api/v1/", include(router.urls)),
    re_path(r"^api/v1/stats/$", StatsApiViewset.as_view(), name="get_score"),
    re_path(r"^api/v1/urlcheck/$", UrlCheckApiViewset.as_view(), name="url_check"),
    re_path(r"^api/v1/hunt/$", BugHuntApiViewset.as_view(), name="hunt_details"),
    re_path(r"^api/v2/hunts/$", BugHuntApiViewsetV2.as_view(), name="hunts_detail_v2"),
    re_path(r"^api/v1/userscore/$", get_score, name="get_score"),
    re_path(r"^authenticate/", CustomObtainAuthToken.as_view()),
    re_path(r"^api/v1/createwallet/$", create_wallet, name="create_wallet"),
    re_path(r"^api/v1/count/$", issue_count, name="api_count"),
    re_path(r"^api/v1/contributors/$", contributors, name="api_contributor"),
    path("project/<slug:slug>/", ProjectDetailView.as_view(), name="project_view"),
    path("projects/<slug:slug>/badge/", ProjectBadgeView.as_view(), name="project-badge"),
    re_path(r"^report-ip/$", ReportIpView.as_view(), name="report_ip"),
    re_path(r"^reported-ips/$", ReportedIpListView.as_view(), name="reported_ips_list"),
    re_path(r"^feed/$", feed, name="feed"),
    re_path(
        r"^api/v1/createissues/$",
        csrf_exempt(IssueCreate.as_view()),
        name="issuecreate",
    ),
    re_path(
        r"^api/v1/search/$",
        csrf_exempt(search_issues),
        name="search_issues",
    ),
    re_path(
        r"^api/v1/delete_issue/(?P<id>\w+)/$",
        csrf_exempt(delete_issue),
        name="delete_api_issue",
    ),
    re_path(
        r"^api/v1/remove_user_from_issue/(?P<id>\w+)/$",
        csrf_exempt(remove_user_from_issue),
        name="remove_api_user_from_issue",
    ),
    re_path(
        r"^api/v1/issue/update/$",
        csrf_exempt(UpdateIssue),
        name="update_api_issue",
    ),
    re_path(r"^api/v1/scoreboard/$", get_scoreboard, name="api_scoreboard"),
    re_path(
        r"^api/v1/terms/$",
        csrf_exempt(TemplateView.as_view(template_name="mobile_terms.html")),
        name="api_terms",
    ),
    re_path(
        r"^api/v1/about/$",
        csrf_exempt(TemplateView.as_view(template_name="mobile_about.html")),
        name="api_about",
    ),
    re_path(
        r"^api/v1/privacypolicy/$",
        csrf_exempt(TemplateView.as_view(template_name="mobile_privacy.html")),
        name="api_privacypolicy",
    ),
    re_path(
        r"^contribute/$",
        TemplateView.as_view(template_name="contribute.html"),
        name="contribution_guidelines",
    ),
    path("select_contribution/", select_contribution, name="select_contribution"),
    path(
        "distribute_bacon/<int:contribution_id>/",
        distribute_bacon,
        name="distribute_bacon",
    ),
    path("activity/like/<int:id>/", like_activity, name="like_activity"),
    path("activity/dislike/<int:id>/", dislike_activity, name="dislike_activity"),
    path("activity/approve/<int:id>/", approve_activity, name="approve_activity"),
    re_path(r"^tz_detect/", include("tz_detect.urls")),
    # re_path(r"^tellme/", include("tellme.urls")),
    re_path(r"^ratings/", include("star_ratings.urls", namespace="ratings")),
    path("robots.txt", robots_txt),
    re_path(r"^contributors/$", contributors_view, name="contributors"),
    # users
    path("users/", users_view, name="users"),
    # company specific urls :
    path("company/", RegisterCompanyView.as_view(), name="register_company"),
    path("company/dashboard/", company_view, name="company_view"),
    path(
        "company/<int:id>/dashboard/analytics/",
        CompanyDashboardAnalyticsView.as_view(),
        name="company_analytics",
    ),
    path(
        "company/<int:id>/dashboard/integrations/",
        CompanyDashboardIntegrations.as_view(),
        name="company_manage_integrations",
    ),
    path(
        "company/<int:id>/dashboard/bugs/",
        CompanyDashboardManageBugsView.as_view(),
        name="company_manage_bugs",
    ),
    path(
        "company/<int:id>/dashboard/domains/",
        CompanyDashboardManageDomainsView.as_view(),
        name="company_manage_domains",
    ),
    path(
        "company/<int:id>/dashboard/roles/",
        CompanyDashboardManageRolesView.as_view(),
        name="company_manage_roles",
    ),
    path(
        "company/<int:id>/dashboard/bughunts/",
        CompanyDashboardManageBughuntView.as_view(),
        name="company_manage_bughunts",
    ),
    path("company/dashboard/end_bughunt/<int:pk>", EndBughuntView.as_view(), name="end_bughunt"),
    path("company/<int:id>/dashboard/add_bughunt/", AddHuntView.as_view(), name="add_bughunt"),
    path("company/<int:id>/dashboard/add_domain/", AddDomainView.as_view(), name="add_domain"),
    path(
        "company/<int:id>/dashboard/add_slack_integration/",
        AddSlackIntegrationView.as_view(),
        name="add_slack_integration",
    ),
    path(
        "company/<int:id>/dashboard/edit_domain/<int:domain_id>/",
        AddDomainView.as_view(),
        name="edit_domain",
    ),
    path("company/domain/<int:pk>/", login_required(DomainView.as_view()), name="view_domain"),
    path("company/delete_prize/<int:prize_id>/<int:company_id>", delete_prize, name="delete_prize"),
    path("company/edit_prize/<int:prize_id>/<int:company_id>", edit_prize, name="edit_prize"),
    path("company/accept_bug/<int:issue_id>/<str:reward_id>/", accept_bug, name="accept_bug"),
    path(
        "company/accept_bug/<int:issue_id>/<str:no_reward>/",
        accept_bug,
        name="accept_bug_no_reward",
    ),
    path(
        "company/delete_manager/<int:manager_id>/<int:domain_id>/",
        delete_manager,
        name="delete_manager",
    ),
    path("sponsor/", sponsor_view, name="sponsor"),
    path("donate/", donate_view, name="donate"),
    path("companies/", DomainListView.as_view(), name="domain_lists"),
    path("trademarks/", trademark_search, name="trademark_search"),
    path("generate_bid_image/<int:bid_amount>/", generate_bid_image, name="generate_bid_image"),
    path("bidding/", SaveBiddingData, name="BiddingData"),
    path("select_bid/", select_bid, name="select_bid"),
    path("get_unique_issues/", get_unique_issues, name="get_unique_issues"),
    path("change_bid_status/", change_bid_status, name="change_bid_status"),
    path("fetch-current-bid/", fetch_current_bid, name="fetch_current_bid"),
    path("Submitpr/", submit_pr, name="submit_pr"),
    path("weekly-report/", weekly_report, name="weekly_report"),
    path("suggestion/add/", add_suggestions, name="add_suggestions"),
    path("suggestion/", view_suggestions, name="view_suggestions"),
    path("suggestion/vote/", vote_suggestions, name="vote_suggestions"),
    path("suggestion/set-vote-status/", set_vote_status, name="set_vote_status"),
    re_path(
        r"^trademarks/query=(?P<slug>[\w\s\W]+)",
        trademark_detailview,
        name="trademark_detailview",
    ),
    path(
        "update_bch_address/",
        update_bch_address,
        name="update_bch_address",
    ),
    path("api/chatbot/conversation/", chatbot_conversation, name="chatbot_conversation"),
    path("blt-tomato/", blt_tomato, name="blt-tomato"),
    path(
        "api/v1/projects/",
        ProjectViewSet.as_view({"get": "list", "post": "create", "patch": "update"}),
        name="projects_api",
    ),
    path("auth/delete", AuthApiViewset.as_view({"delete": "delete"}), name="auth-delete-api"),
    path("api/v1/tags", TagApiViewset.as_view({"get": "list", "post": "create"}), name="tags-api"),
    path("sizzle/", sizzle, name="sizzle"),
    path("check-in/", checkIN, name="checkIN"),
    path("add-sizzle-checkin/", add_sizzle_checkIN, name="add_sizzle_checkin"),
    path("check-in/<int:report_id>/", checkIN_detail, name="checkIN_detail"),
    path("sizzle-docs/", sizzle_docs, name="sizzle-docs"),
    path("api/timelogsreport/", TimeLogListAPIView, name="timelogsreport"),
    path("time-logs/", TimeLogListView, name="time_logs"),
    path("sizzle-daily-log/", sizzle_daily_log, name="sizzle_daily_log"),
    path(
        "user-sizzle-report/<str:username>/",
        user_sizzle_report,
        name="user_sizzle_report",
    ),
    path("delete_time_entry/", delete_time_entry, name="delete_time_entry"),
    path("assign-badge/<str:username>/", assign_badge, name="assign_badge"),
    path("github-webhook/", github_webhook, name="github-webhook"),
    # blog urls
    path("blog/", PostListView.as_view(), name="blog"),
    path("blog/new/", PostCreateView.as_view(), name="post_create"),
    path("blog/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path("blog/<slug:slug>/edit/", PostUpdateView.as_view(), name="post_update"),
    path("blog/<slug:slug>/delete/", PostDeleteView.as_view(), name="post_delete"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        re_path(r"^__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
