# Generated by Django 5.1.8 on 2025-11-16 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICommentaryTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=20)),
                ("template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["event_type"],
            },
        ),
        migrations.CreateModel(
            name="MonitoredEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all_github", "All GitHub"),
                            ("organization", "Organization"),
                            ("repository", "Repository"),
                            ("tag", "Tag"),
                            ("curated_list", "Curated List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("github_url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Monitored Entities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monitored_entities",
                    models.ManyToManyField(related_name="channels", to="sportscaster.monitoredentity"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sportscaster_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_type", models.CharField(default="stars", max_length=50)),
                ("current_value", models.IntegerField(default=0)),
                ("previous_value", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monitored_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="sportscaster.monitoredentity",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("monitored_entity", "metric_type")},
            },
        ),
        migrations.CreateModel(
            name="GitHubEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("star", "Star"),
                            ("fork", "Fork"),
                            ("pull_request", "Pull Request"),
                            ("commit", "Commit"),
                            ("release", "Release"),
                            ("issue", "Issue"),
                            ("watch", "Watch"),
                            ("hackathon", "Hackathon Announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_data", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed", models.BooleanField(default=False)),
                ("commentary_generated", models.BooleanField(default=False)),
                ("commentary_text", models.TextField(blank=True, null=True)),
                (
                    "monitored_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="sportscaster.monitoredentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="sportscaste_timesta_3613af_idx"),
                    models.Index(fields=["event_type"], name="sportscaste_event_t_977ddb_idx"),
                    models.Index(fields=["processed"], name="sportscaste_process_41a1e3_idx"),
                ],
            },
        ),
    ]
