---
name: Auto-Assign New Issues to Copilot

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign-to-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to copilot
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            try {
              // Assign the issue to copilot
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: ['copilot']
              });

              console.log(
                `Successfully assigned issue #${issueNumber} to copilot`
              );
            } catch (error) {
              console.error(
                `Error assigning issue to copilot: ${error.message}`
              );
            }
