name: Update Bid Badge

on:
  issue_comment:
    types: [created, edited]

jobs:
  update_bid_badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse bid comment
        id: parse_bid
        run: |
          bid_amount=$(echo "${{ github.event.comment.body }}" | grep -oE '\$[0-9]+')
          echo "::set-output name=bid_amount::$bid_amount"

      - name: Generate badge URL
        id: generate_badge_url
        run: |
          bid_amount="${{ steps.parse_bid.outputs.bid_amount }}"
          badge_url="https://blt.owasp.org/generate_bid_image/bid=$bid_amount"
          echo "::set-output name=badge_url::$badge_url"

      - name: Update issue comment with badge
        run: |
          badge_url="${{ steps.generate_badge_url.outputs.badge_url }}"
          curl -X POST https://api.github.com/repos/:owner/:repo/issues/${{ github.event.issue.number }}/comments \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"![Bid Badge]($badge_url)\"}"
