name: Django Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: browser-actions/setup-geckodriver@latest
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libmemcached-dev xvfb
        python -m pip install --upgrade pipenv wheel
        pipenv install

    - name: Run migrations
      run: pipenv run python manage.py migrate
    - name: Run collectstatic
      run: pipenv run python manage.py collectstatic --noinput
    - name: Run tests
      run: xvfb-run --auto-servernum pipenv run python manage.py test
