name: Django Test

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: nanasess/setup-chromedriver@v2
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.2
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.2
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Collect static files
      run: poetry run python manage.py collectstatic --noinput
    - name: Run tests
      run: poetry run xvfb-run --auto-servernum python manage.py test -v 3 --failfast
