name: PRs reviews reminder

on:
  schedule:
    # Runs every hour, between 14:00 and 21:00, Monday through Friday.
    - cron: "0,30 14-21 * * 1-5"


jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v2.7.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: ${{ secrets.SLACK_PR_REMINDER_WEBHOOK_URL }}
        provider: 'slack' # Required (slack, rocket or msteams)
        channel: '#project-blt-prs' # Optional, eg: #general
